noh={R:function(a){a&&(this.message=a)}};noh.R.prototype=Error("Not implemented");noh.da=function(a){a&&(this.message=a)};noh.da.prototype=new noh.R("Operation not supported");noh.Fa="html head body script meta title link div p span a img br hr em i strong table tr th td thead tbody tfoot colgroup col ul ol li dl dt dd h1 h2 h3 h4 h5 h6 form fieldset input textarea label select option b pre code button kbd".split(" ");noh.body=function(a){return new noh.a("body",arguments)};
noh.link=function(a){return new noh.a("link",arguments)};noh.e=function(a){return new noh.a("div",arguments)};noh.g=function(a){return new noh.a("p",arguments)};noh.span=function(a){return new noh.a("span",arguments)};noh.D=function(a){return new noh.a("a",arguments)};noh.Ya=function(a){return new noh.a("img",arguments)};noh.Ja=function(a){return new noh.a("br",arguments)};noh.Va=function(a){return new noh.a("hr",arguments)};noh.Pa=function(a){return new noh.a("em",arguments)};
noh.Wa=function(a){return new noh.a("i",arguments)};noh.za=function(a){return new noh.a("strong",arguments)};noh.table=function(a){return new noh.a("table",arguments)};noh.Ca=function(a){return new noh.a("tr",arguments)};noh.qb=function(a){return new noh.a("th",arguments)};noh.Ba=function(a){return new noh.a("td",arguments)};noh.rb=function(a){return new noh.a("thead",arguments)};noh.tbody=function(a){return new noh.a("tbody",arguments)};noh.pb=function(a){return new noh.a("tfoot",arguments)};
noh.Na=function(a){return new noh.a("colgroup",arguments)};noh.Ma=function(a){return new noh.a("col",arguments)};noh.sb=function(a){return new noh.a("ul",arguments)};noh.eb=function(a){return new noh.a("ol",arguments)};noh.$a=function(a){return new noh.a("li",arguments)};noh.ga=function(a){return new noh.a("dl",arguments)};noh.W=function(a){return new noh.a("dt",arguments)};noh.V=function(a){return new noh.a("dd",arguments)};noh.ka=function(a){return new noh.a("h1",arguments)};
noh.Ra=function(a){return new noh.a("h2",arguments)};noh.Sa=function(a){return new noh.a("h3",arguments)};noh.Y=function(a){return new noh.a("h4",arguments)};noh.Ta=function(a){return new noh.a("h5",arguments)};noh.Ua=function(a){return new noh.a("h6",arguments)};noh.form=function(a){return new noh.a("form",arguments)};noh.Qa=function(a){return new noh.a("fieldset",arguments)};noh.input=function(a){return new noh.a("input",arguments)};noh.ob=function(a){return new noh.a("textarea",arguments)};
noh.label=function(a){return new noh.a("label",arguments)};noh.select=function(a){return new noh.a("select",arguments)};noh.fb=function(a){return new noh.a("option",arguments)};noh.ea=function(a){return new noh.a("b",arguments)};noh.ua=function(a){return new noh.a("pre",arguments)};noh.code=function(a){return new noh.a("code",arguments)};noh.button=function(a){return new noh.a("button",arguments)};noh.ma=function(a){return new noh.a("kbd",arguments)};noh.text=function(a){return new noh.S(a)};
noh.l=function(a,b,c){c=c?c:{j:{},c:[]};if(a instanceof noh.m)c.c.push(a);else if("string"===typeof a)c.c.push(noh.text(a));else if(noh.n.la(a))for(b=void 0===b?0:b;b<a.length;++b)noh.l(a[b],0,c);else if(a instanceof Object)$.extend(c.j,a);else if(void 0!==a&&null!==a)throw new TypeError("Unknown argument type: "+typeof a+" value: "+String(a));return c};noh.n={};noh.n.push=function(a,b){return b.push.apply(b,a)};noh.n.indexOf=function(a,b){for(var c=0;c<b.length;++c)if(a==b[c])return c;return-1};
noh.n.Ha=function(a,b){if(null===b)return null;for(var c={},d=0;d<a.length;++d)c[a[d]]=b[d];return c};noh.n.cb=function(a,b){if(null===b)return null;for(var c=[],d=0;d<a.length;++d)c.push(b[a[d]]);return c};noh.n.la=function(a){var b=Object.prototype.hasOwnProperty,c;return null!=a&&(a instanceof jQuery||"number"===typeof(c=a.length)&&(0<=c&&b.call(a,0)&&b.call(a,c-1)||jQuery.isArray(a)))};noh.s={};noh.s.Z=function(a,b){a.length>b&&(a=a.substr(0,b-3)+"...");return a};
noh.s.prefix=function(a,b,c){for(;a.length<c;)a=b+a;return a};noh.m=function(){this.length=0;this.b=this.h=this.parent=null};noh.m.prototype.add=function(a){this.h.appendChild(a.h);a.parent=this;Array.prototype.push.call(this,a);return this};noh.S=function(a){this.text=a;noh.m.call(this);this.h=document.createTextNode(a);this.h.J=this;this.b=$(this.h)};noh.S.prototype=new noh.m;
noh.a=function(a,b){this.tag=a;noh.m.call(this);this.h=document.createElement(a);this.h.J=this;this.b=$(this.h);var c=noh.l(arguments,1),d;for(d in c.j)this.attr(d,c.j[d]);for(d=0;d<c.c.length;++d)this.add(c.c[d])};noh.a.prototype=new noh.m;noh.a.prototype.attr=function(a,b){this.b.attr(a,b);return this};noh.a.prototype.css=function(a,b){this.b.css(a,b);return this};noh.a.prototype.on=function(a,b){this.b.on(a,b);return this};function e(a,b){a.b.addClass(b);return a}
function h(a,b){a.b.removeClass(b);return a}noh.scroll=function(a,b){$("html,body").animate({scrollTop:a},b?b:1E3)};noh.a.prototype.scroll=function(a){noh.scroll(this.b.offset().top,a);return this};noh.Aa=function(a){var b=noh.l(arguments);return noh.table(b.j,noh.tbody(noh.Ca(b.c)))};noh.nb=function(a){for(var b=noh.l(arguments),c=[],d=0;d<b.children.length;++d)c.push(j.Ba(b.c[d]));return noh.Aa({"class":"noh bar"},b.j,c)};
noh.ib=function(a){return noh.e({style:"margin:10px; padding:10px; border:solid 2px"},arguments)};noh.f={};noh.f.wa=function(){return noh.span("Simpleeeee! kind of man!").css("padding",10).css("background-color","lightgray").css("border","solid 2px")};noh.f.ja=function(){return noh.span("Daaaaa..").css("padding",20).css("background-color","gray").css("border","solid 4px")};
noh.f.va=function(){return noh.span({style:"padding: 25px; font-size:xx-large; color:red; background-color:yellow; border:solid 1px red; border-radius:40px"},":-)")};noh.f.tb=function(){return noh.span({style:"padding:15px; color:white; background-color:white; border:solid 2px white"},"White on white")};noh.f.kb=function(){return noh.span({style:"padding:10px; color:red; background-color:pink; border:solid 2px red"},":*")};noh.f.Xa=function(){return noh.e(noh.f.wa(),noh.f.ja(),noh.f.va())};
noh.f.color=function(a){return noh.span({style:"padding:8px"},"C").css("color",a).css("background-color",a)};noh.f.hb=function(a){for(var b=[],c=0;c<a;++c)b.push(noh.f.color("hsl("+360*c/a+",100%,50%)"));return noh.span(b)};noh.u=function(a,b){return noh.ua({"class":"brush: "+a+"; toolbar: false"},b)};noh.lb=function(a){return noh.u("js",a.toString())};
noh.gb=function(a){var b=e(noh.e(arguments),"noh overlay");b.show=function(a){a=void 0===a?this:this[a];if(!a.b.hasClass("hidden"))return b;(this.b.hasClass("left")||this.b.hasClass("right"))&&a.css("left","").css("right","");(this.b.hasClass("top")||this.b.hasClass("bottom"))&&a.css("top","").css("bottom","");e(h(a,"hidden"),"visible");return this};b.hide=function(a){a=void 0===a?this:this[a];if(a.b.hasClass("hidden"))return b;var d=$(window).width(),f=$(window).height(),g=a.b.outerWidth(!0),m=a.b.outerHeight(!0),
k=a.b.offset(),n=k.left,k=k.top-$(document).scrollTop(),d=d-n-g,f=f-k-m;this.b.hasClass("left")?a.css("left",""+(-n-g-5)+"px"):this.b.hasClass("right")?a===this?a.css("right",""+(-d-g-5)+"px"):a.css("left",""+(g+d+5)+"px"):this.b.hasClass("top")?a.css("top",""+(-k-m-5)+"px"):this.b.hasClass("bottom")&&(a===this?a.css("bottom",""+(-f-m-5)+"px"):a.css("top",""+(m+f+5)+"px"));e(h(a,"visible"),"hidden");return this};return b};
noh.xa=function(a,b){e(e(a,"noh"),"sleepy");a.fa=void 0===b?1E3:b;a.Ea=function(){e(h(this,"asleep"),"awake");window.clearTimeout(this.K);this.K=window.setTimeout(function(){a.ba()},a.fa)};a.ba=function(){window.clearTimeout(this.K);this.K=void 0;e(h(this,"awake"),"asleep")};a.ba();return a};noh.N=function(){};noh.N.prototype.H=function(){};noh.N.prototype.r=function(){};
noh.v=function(a){var b=e(noh.e(arguments),"noh blind content");noh.a.call(this,"div",b);e(this,"noh blind");this.t=b;this.r(!1);var c=this;this.b.show(function(){c.r(c.H())})};noh.v.prototype=new noh.a("div");noh.v.prototype.H=function(){return this.ha};
noh.v.prototype.r=function(a){var b=this.b,c=this.t.b,d=c.width(),f=c.height();c.css("clip","rect(0px "+d+"px "+(a?f:0)+"px 0px");a?(h(this.t,"hidden"),e(this.t,"visible")):(h(this.t,"visible"),e(this.t,"hidden"));b.width(d);b.height(a?f:0);this.ha=a;return this};noh.T=function(a){return new noh.v(arguments)};noh.O=function(){};noh.O.prototype.selected=function(){};noh.O.prototype.select=function(){};
noh.C=function(a){for(var b=noh.l(arguments),c=0;c<b.c.length;++c){var d=noh.T(b.c[c]);b.c[c]=d;d.sa=c}noh.a.call(this,"div",b.j,b.c);e(this,"noh oneof");this.d=-1};noh.C.prototype=new noh.a("div");noh.C.prototype.selected=function(){return this.d};noh.C.prototype.select=function(a){a instanceof noh.m?a=a.sa:null===a&&(a=-1);var b=this.length;if(-1>a||a>=b)a=-1;-1!=this.d&&this[this.d].r(!1);-1!=a&&this[a].r(!0);this.d=a;return this};noh.ta=function(a){return new noh.C(arguments)};
noh.Oa=function(a){var b=e(noh.e(arguments),"noh details content"),c=noh.T(b),b=e(noh.button("details..."),"noh details button").attr("title","show/hide details");b.on("click",function(){c.r(!c.H())});return e(noh.e(noh.e(b),noh.e(c)),"noh details")};
noh.q=function(a,b,c,d){for(var f=noh.l(arguments,3),g=0;g<f.c.length;++g){var m=e(noh.e(f.c[g]),"noh reel element");f.c[g]=m}noh.a.call(this,"div",f.j,f.c);e(this,"noh reel");this.i=a;this.rotation=0;this.width=b;this.height=c;l(this);var k=this;this.b.show(function(){k.update()});this.d=-1};noh.q.prototype=new noh.a("div");noh.q.prototype.selected=function(){return this.d};
noh.q.prototype.select=function(a){if(-1>a||a>=this.length)a=-1;if(this.d==a)return this;-1!=this.d&&h(p(this,this.d),"selected");-1!=a&&e(p(this,a),"selected");this.d=a;return this};
function l(a){var b=0;if("automatic"==a.width)for(var c=0;c<a.length;++c)esize=a[c].b.width(),esize>b&&(b=esize);else if("dynamic"==a.width)for(c=0;c<a.i;++c)esize=p(a,c).b.width(),esize>b&&(b=esize);else b=a.width;a.css("min-width",b).css("max-width",b).css("width",b);b=0;if("automatic"==a.height){for(c=0;c<a.length;++c)esize=a[c].b.height(),esize>b&&(b=esize);b*=a.i}else if("dynamic"==a.height){for(c=0;c<a.i;++c)esize=p(a,c).b.height(),esize>b&&(b=esize);b*=a.i}else b=a.height;a.css("min-height",
b).css("max-height",b).css("height",b);a.X=b}function q(a,b){for(;0>b;)b+=a.length;for(;b>=a.length;)b-=a.length;return b}function p(a,b){return a[q(a,b-a.rotation)]}
noh.q.prototype.update=function(a){void 0!==a&&(this.i=a);l(this);for(a=0;a<this.length;++a){var b=p(this,a);h(b,"selected");a<this.i?(e(h(b,"hidden"),"visible"),b.css("top",""+a*this.X/this.i+"px")):(e(h(b,"visible"),"hidden"),b.css("top",""+(this.length-a-1)*this.X/(this.length-this.i)+"px"))}-1!=this.d&&e(p(this,this.d),"selected");return this};noh.q.prototype.rotate=function(a){this.rotation=q(this,this.rotation+a);return this.update()};
noh.k=function(a,b,c,d){var f=noh.l(arguments,3);return new noh.q(a,b,c,f.j,f.c)};noh.ia=function(){var a=noh.ka("NOH");e(a,"fancy");if(-1!=noh.n.indexOf(a.tag,["h1","h2","h3","h4"]))a.on("click",function(){this.J.scroll()});return a};noh.Da=function(a){var b=/(https?|ftp):\/\//;a=a.split(/\s+/).map(function(a){return b.test(a)?noh.D({href:a,target:"_blank"},a):" "+a+" "});return noh.ma(a)};noh.log={};
noh.log.U=function(a){var b="";0<a.length&&(b+=a[0]);for(var c=1;c<a.length;++c)b=b+" "+a[c].toString();return b};noh.log.ca=function(){};noh.log.ca.prototype.log=function(){};noh.log.G=function(){noh.a.call(this,"div");e(this,"noh log little")};noh.log.G.prototype=new noh.a("div");noh.log.G.prototype.log=function(a,b){if(this.length){var c=Array.prototype.pop.call(this);c.parent=null;this.h.removeChild(c.h)}c=e(e(noh.Da(noh.log.U(b)),"noh log element"),a);this.add(c)};noh.log.na=function(){return new noh.log.G};
noh.log.ya=function(a){var b=noh.log.na();a=noh.xa(b,a);a.oa=a.log;a.log=function(a,b){this.oa(a,b);this.Ea()};return a};noh.log.w=function(){};noh.log.w.prototype.log=function(){};noh.log.w.prototype.info=function(){};noh.log.w.prototype.warn=function(){};noh.log.w.prototype.error=function(){};noh.log.p=function(a){this.o=a};noh.log.p.prototype.log=function(a){this.o.log("info",arguments)};noh.log.p.prototype.info=function(a){this.o.log("info",arguments)};
noh.log.p.prototype.warn=function(a){this.o.log("warning",arguments)};noh.log.p.prototype.error=function(a){this.o.log("error",arguments)};noh.log.p.prototype.debug=function(a){this.o.log("debug",arguments)};noh.log.Za=function(a){return new noh.log.p(a)};noh.log.L=function(a){this.console=a};
noh.log.L.prototype.log=function(a,b){/error/.test(a)?this.console.error.apply(this.console,b):/warning/.test(a)?this.console.warn.apply(this.console,b):/debug/.test(a)&&this.console.debug instanceof Function?this.console.debug.apply(this.console,b):this.console.info.apply(this.console,b)};noh.log.Ka=function(a){return new noh.log.L(a)};noh.log.Q=function(a){this.$=a};noh.log.Q.prototype.log=function(a,b){for(var c=0;c<this.$.length;++c)this.$[c].log(a,b)};noh.log.bb=function(a){return new noh.log.Q(a)};
noh.log.M=function(a,b){this.o=a;this.filter=b};noh.log.M.prototype.log=function(a,b){this.o.log(a,this.filter(b))};noh.log.filter=function(a,b){return new noh.log.M(a,b)};noh.log.Ga=function(a){return noh.log.filter(a,function(a){var c=new Date;return["["+noh.s.prefix(""+c.getHours(),"0",2)+":"+noh.s.prefix(""+c.getMinutes(),"0",2)+":"+noh.s.prefix(""+c.getSeconds(),"0",2)+"]"].concat(Array.prototype.slice.call(a,0))})};
noh.log.Z=function(a,b){return noh.log.filter(a,function(a){return[noh.s.Z(noh.log.U(a),b)]})};noh.log.k=function(a,b){for(var c=2*a+1,d=void 0===b?1E4:b,f=[],g=0;g<c;++g)f.push(noh.log.ya(d));c=noh.k(a,"automatic","automatic",f);c.select(a-1);logger=e(noh.e(c),"noh log reel");logger.k=c;logger.log=function(a,b){p(this.k,this.k.i)[0].log(a,b);this.k.rotate(-1)};logger.jb=function(a){var b=a-this.k.i;this.k.i=a;this.k.rotate(b)};return logger};
noh.La=function(a){var b=e(noh.input().attr("type","text").attr("size",a).attr("placeholder",'alert("hello world")'),"noh cmdline");a=e(noh.button(String.fromCharCode(8629)).attr("title","Press enter to run the command."),"noh cmdline");var c=e(noh.e(b,a).css("display","inline-block"),"noh cmdline");c.aa=function(){var a=b.b.val();console.log(a);try{var c=eval(a);void 0!==c&&console.log(c)}catch(g){console.error(g)}b.b.val("")};b.on("keypress",function(a){13==a.which&&c.aa()});a.on("click",function(){c.aa()});
return c};noh.P=function(){};noh.P.prototype.selected=function(){};noh.P.prototype.toggle=function(){};noh.B=function(a){noh.a.call(this,"div",{"class":"noh menu item"},a);this.on("click",function(){this.J.toggle();return!1})};noh.B.prototype=new noh.a("div");noh.B.prototype.toggle=function(){this.b.toggleClass("selected")};noh.B.prototype.selected=function(){return this.b.hasClass("selected")};noh.ab=function(a){return new noh.B(a)};
noh.Ia=function(a,b){var c=noh.ta(b),d=noh.e(noh.e(a),noh.e(c));a.F=a.toggle;a.toggle=function(){d.toggle()};d.toggle=function(){a.F();c.select(this.selected()?0:-1)};d.selected=function(){return a.selected()};return d};noh.A=function(a){var b=noh.l(arguments);noh.a.call(this,"div",b.j,b.c);this.I=b.c;for(b=0;b<this.I.length;++b){var c=this.items[b];c.selected()&&c.toggle();c.ra=this;c.qa=b;c.F=c.toggle;c.toggle=function(){this.ra.select(this.selected()?-1:this.qa)}}this.d=-1};noh.A.prototype=new noh.a("div");
noh.A.prototype.selected=function(){return this.d};noh.A.prototype.select=function(a){-1!=this.d&&this.I[selected_].F();this.d=a;-1!=a&&this.I[a].F()};noh.pa=function(a){return new noh.A(arguments)};noh.mb=function(a,b){var c=bigmenuitem(a,b);c.pa=b;return c};$(document).ready(function(){var a=$("#noh_doc");if(0!=a.length){var b=noh.e({style:"margin:10px"},noh.ia(),noh.Y("(No HTML library)"),noh.g("The ",noh.za("NOH")," library allows to create the HTML documents dynamicly in pure JavaScript ","(with almost no HTML code at all). "),noh.g("The basic idea is that for every HTML tag, we have special JavaScript function, that generates appropriate DOM element."),noh.g(noh.Y("Example:"),noh.ga(noh.W("Instead of HTML code like this:"),noh.V(noh.u("html",'<div id="someid">\n    <h2>EXAMPLE</h2>\n    <p>\n        <h4>Some header</h4>\n        Some content\n    </p>\n    <p>\n        <h4>Other header</h4>\n        Other content\n    </p>\n</div>\n')),
noh.W("We write JS code like this:"),noh.V(noh.u("js",'noh.div({id:"someid"},\n    noh.h2("EXAMPLE"),\n    noh.p(noh.h4("Some header"),"Some content"),\n    noh.p(noh.h4("Other header"),"Other content")\n)\n')))),noh.g("We have a function for every HTML element like: ",noh.u("js","noh.table, noh.tr, noh.td, noh.div, noh.span etc..; "),"but also we have functions that constructs many specialized and more complex Nodes that have some dynamic behaviour ","implemented like: ",noh.u("js","noh.menu, noh.oneof, noh.details, noh.syntaxhl, noh.srccode, noh.llogger, noh.plogger")),
noh.g("TODO: more introduction - how it replaces templates (there are other libraries, but...), that many times it's better to generate content from js because html is verbose (long download) etc.."),noh.g("TODO: more examples - with not standard tags, but still simple; with attributes and styles; different ways to insert attributes and nodes - a few examples giving the same result"),noh.g("TODO: about initialization; about options; about pollute:true and why we should avoid it in bigger projects;"),
noh.g("TODO: example that adds some dynamic behavoiur, and serves as a kind of template"),noh.g("TODO: About compiled versions of pages - min1, min2, min3"),noh.g("The NOH library requires a jQuery library. (tested on: jquery-1.10.2.js)"),noh.g("Please check the ",noh.D({href:"noh_tests.html"},noh.ea("noh_tests.html"))," file! It demonstrates all available elements in action."),noh.g("Additional API documentation generated with ",noh.D({href:"http://usejsdoc.org/"},"jsdoc3")," will be available here: ",
noh.D({href:"apidoc/index.html"},"NOH API documentation")));a[0].appendChild(b.h);SyntaxHighlighter.all()}});
