function e(a){return new g("div",arguments)}function h(a){return new g("p",arguments)}function l(a){return new g("span",arguments)}function n(a){return new g("a",arguments)}function p(a){return new g("br",arguments)}function aa(a){return new g("table",arguments)}function ba(a){return new g("tr",arguments)}function q(a){return new g("td",arguments)}function ca(a){return new g("tbody",arguments)}function da(a){return new g("ul",arguments)}function s(a){return new g("li",arguments)}
function ea(a){return new g("dl",arguments)}function fa(a){return new g("dt",arguments)}function ga(a){return new g("dd",arguments)}function t(a){return new g("h1",arguments)}function ha(a){return new g("h2",arguments)}function u(a){return new g("h3",arguments)}function w(a){return new g("h4",arguments)}function ia(a){return new g("h5",arguments)}function ja(a){return new g("h6",arguments)}function ka(a){return new g("input",arguments)}function la(a){return new g("pre",arguments)}
function x(a){return new g("button",arguments)}function ma(a){return new g("kbd",arguments)}function y(a,b,c){b=void 0===b?0:b;c=c?c:{f:{},b:[]};if(a instanceof z)c.b.push(a);else if("string"===typeof a)c.b.push(new na(a));else if(oa(a))for(;b<a.length;++b)y(a[b],0,c);else if(a instanceof Object)$.extend(c.f,a);else if(void 0!==a&&null!==a)throw new TypeError("Unknown argument type: "+typeof a+" value: "+String(a));return c}
function pa(a){for(var b=["h1","h2","h3","h4"],c=0;c<b.length;++c)if(a==b[c])return c;return-1}function oa(a){if(void 0==a||null==a)return!1;if(a instanceof jQuery||jQuery.isArray(a))return!0;var b=a.length;if("number"!==typeof b)return!1;if(0==b)return!0;if(0>b)return!1;var c=Object.prototype.hasOwnProperty;return c.call(a,0)&&c.call(a,b-1)?!0:!1}function A(a){for(;2>a.length;)a="0"+a;return a}function z(){this.length=0;this.a=this.c=this.parent=null}
z.prototype.add=function(a){this.c.appendChild(a.c);a.parent=this;Array.prototype.push.call(this,a);return this};function na(a){this.text=a;z.call(this);this.c=document.createTextNode(a);this.c.m=this;this.a=$(this.c)}na.prototype=new z;function g(a,b){this.tag=a;z.call(this);this.c=document.createElement(a);this.c.m=this;this.a=$(this.c);var c=y(arguments,1),d;for(d in c.f)this.attr(d,c.f[d]);for(d=0;d<c.b.length;++d)this.add(c.b[d])}g.prototype=new z;
g.prototype.attr=function(a,b){this.a.attr(a,b);return this};g.prototype.css=function(a,b){this.a.css(a,b);return this};g.prototype.on=function(a,b){this.a.on(a,b);return this};function B(a,b){a.a.addClass(b);return a}function C(a,b){a.a.removeClass(b);return a}function qa(a,b){$("html,body").animate({scrollTop:a},b?b:1E3)}g.prototype.scroll=function(a){qa(this.a.offset().top,a);return this};function ra(a){var b=y(arguments);return aa(b.f,ca(ba(b.b)))}
function D(a){return e({style:"margin:10px; padding:10px; border:solid 2px"},arguments)}function E(){return l("Simpleeeee! kind of man!").css("padding",10).css("background-color","lightgray").css("border","solid 2px")}function F(){return l("Daaaaa..").css("padding",20).css("background-color","gray").css("border","solid 4px")}function G(){return l({style:"padding: 25px; font-size:xx-large; color:red; background-color:yellow; border:solid 1px red; border-radius:40px"},":-)")}
function H(){return l({style:"padding:10px; color:red; background-color:pink; border:solid 2px red"},":*")}function I(a){return l({style:"padding:8px"},"C").css("color",a).css("background-color",a)}function J(a){for(var b=[],c=0;c<a;++c)b.push(I("hsl("+360*c/a+",100%,50%)"));return l(b)}function K(a,b){return la({"class":"brush: "+a+"; toolbar: false"},b)}
function L(a){var b=B(e(arguments),"noh overlay");b.show=function(a){a=void 0===a?this:this[a];if(!a.a.hasClass("hidden"))return b;(this.a.hasClass("left")||this.a.hasClass("right"))&&a.css("left","").css("right","");(this.a.hasClass("top")||this.a.hasClass("bottom"))&&a.css("top","").css("bottom","");B(C(a,"hidden"),"visible");return this};b.hide=function(a){a=void 0===a?this:this[a];if(a.a.hasClass("hidden"))return b;var d=$(window).width(),f=$(window).height(),k=a.a.outerWidth(!0),m=a.a.outerHeight(!0),
r=a.a.offset(),v=r.left,r=r.top-$(document).scrollTop(),d=d-v-k,f=f-r-m;this.a.hasClass("left")?a.css("left",""+(-v-k-5)+"px"):this.a.hasClass("right")?a===this?a.css("right",""+(-d-k-5)+"px"):a.css("left",""+(k+d+5)+"px"):this.a.hasClass("top")?a.css("top",""+(-r-m-5)+"px"):this.a.hasClass("bottom")&&(a===this?a.css("bottom",""+(-f-m-5)+"px"):a.css("top",""+(m+f+5)+"px"));B(C(a,"visible"),"hidden");return this};return b}
function sa(a,b){B(B(a,"noh"),"sleepy");a.t=void 0===b?1E3:b;a.D=function(){B(C(this,"asleep"),"awake");window.clearTimeout(this.o);this.o=window.setTimeout(function(){a.s()},a.t)};a.s=function(){window.clearTimeout(this.o);this.o=void 0;B(C(this,"awake"),"asleep")};a.s();return a}function M(a){var b=B(e(arguments),"noh blind content");g.call(this,"div",b);B(this,"noh blind");this.j=b;this.h(!1);var c=this;this.a.show(function(){c.h(c.l())})}M.prototype=new g("div");M.prototype.l=function(){return this.u};
M.prototype.h=function(a){var b=this.a,c=this.j.a,d=c.width(),f=c.height();c.css("clip","rect(0px "+d+"px "+(a?f:0)+"px 0px");a?(C(this.j,"hidden"),B(this.j,"visible")):(C(this.j,"visible"),B(this.j,"hidden"));b.width(d);b.height(a?f:0);this.u=a;return this};function N(a){return new M(arguments)}function O(a){for(var b=y(arguments),c=0;c<b.b.length;++c){var d=N(b.b[c]);b.b[c]=d;d.w=c}g.call(this,"div",b.f,b.b);B(this,"noh oneof");this.e=-1}O.prototype=new g("div");
O.prototype.select=function(a){a instanceof z?a=a.w:null===a&&(a=-1);var b=this.length;if(-1>a||a>=b)a=-1;-1!=this.e&&this[this.e].h(!1);-1!=a&&this[a].h(!0);this.e=a;return this};function ta(a){return new O(arguments)}function ua(a){var b=B(e(arguments),"noh details content"),c=N(b),b=B(x("details..."),"noh details button").attr("title","show/hide details");b.on("click",function(){c.h(!c.l())});b=B(e(e(b),e(c)),"noh details");b.l=function(){return c.l()};b.h=function(a){return c.h(a)};return b}
function P(a,b,c,d){for(var f=y(arguments,3),k=0;k<f.b.length;++k){var m=B(e(f.b[k]),"noh reel element");f.b[k]=m}g.call(this,"div",f.f,f.b);B(this,"noh reel");this.d=a;this.rotation=0;this.width=b;this.height=c;va(this);var r=this;this.a.show(function(){r.update()});this.e=-1}P.prototype=new g("div");P.prototype.select=function(a){if(-1>a||a>=this.length)a=-1;if(this.e==a)return this;-1!=this.e&&C(Q(this,this.e),"selected");-1!=a&&B(Q(this,a),"selected");this.e=a;return this};
function va(a){var b=0,c=0;if("automatic"==a.width)for(var d=0;d<a.length;++d)c=a[d].a.width(),c>b&&(b=c);else if("dynamic"==a.width)for(d=0;d<a.d;++d)c=Q(a,d).a.width(),c>b&&(b=c);else b=a.width;a.css("min-width",b).css("max-width",b).css("width",b);b=0;if("automatic"==a.height){for(d=0;d<a.length;++d)c=a[d].a.height(),c>b&&(b=c);b*=a.d}else if("dynamic"==a.height){for(d=0;d<a.d;++d)c=Q(a,d).a.height(),c>b&&(b=c);b*=a.d}else b=a.height;a.css("min-height",b).css("max-height",b).css("height",b);a.p=
b}function wa(a,b){for(;0>b;)b+=a.length;for(;b>=a.length;)b-=a.length;return b}function Q(a,b){return a[wa(a,b-a.rotation)]}P.prototype.update=function(a){void 0!==a&&(this.d=a);va(this);for(a=0;a<this.length;++a){var b=Q(this,a);C(b,"selected");a<this.d?(B(C(b,"hidden"),"visible"),b.css("top",""+a*this.p/this.d+"px")):(B(C(b,"visible"),"hidden"),b.css("top",""+(this.length-a-1)*this.p/(this.length-this.d)+"px"))}-1!=this.e&&B(Q(this,this.e),"selected");return this};
P.prototype.rotate=function(a){this.rotation=wa(this,this.rotation+a);return this.update()};function R(a,b,c,d){var f=y(arguments,3);return new P(a,b,c,f.f,f.b)}function S(a){B(a,"fancy");if(-1!=pa(a.tag))a.on("click",function(){this.m.scroll()});else if("a"==a.tag){var b=a.a.attr("href");if(b&&0<b.length&&"#"==b[0])a.on("click",function(){qa($($(this).attr("href")).offset().top)})}return a}
function xa(a){var b=/(https?|ftp):\/\//;a=a.split(/\s+/).map(function(a){return b.test(a)?n({href:a,target:"_blank"},a):" "+a+" "});return ma(a)}function ya(a){var b="";0<a.length&&(b+=a[0]);for(var c=1;c<a.length;++c)b=b+" "+a[c].toString();return b}function T(){g.call(this,"div");B(this,"noh log little")}T.prototype=new g("div");T.prototype.log=function(a,b){if(this.length){var c=Array.prototype.pop.call(this);c.parent=null;this.c.removeChild(c.c)}c=B(B(xa(ya(b)),"noh log element"),a);this.add(c)};
function U(a){var b=new T;a=sa(b,a);a.v=a.log;a.log=function(a,b){this.v(a,b);this.D()};return a}function V(a){this.g=a}V.prototype.log=function(a){this.g.log("info",arguments)};V.prototype.info=function(a){this.g.log("info",arguments)};V.prototype.warn=function(a){this.g.log("warning",arguments)};V.prototype.error=function(a){this.g.log("error",arguments)};V.prototype.debug=function(a){this.g.log("debug",arguments)};function W(a){this.console=a}
W.prototype.log=function(a,b){/error/.test(a)?this.console.error.apply(this.console,b):/warning/.test(a)?this.console.warn.apply(this.console,b):/debug/.test(a)&&this.console.debug instanceof Function?this.console.debug.apply(this.console,b):this.console.info.apply(this.console,b)};function za(a){this.q=a}za.prototype.log=function(a,b){for(var c=0;c<this.q.length;++c)this.q[c].log(a,b)};function Aa(a){return new za(a)}function Ba(a,b){this.g=a;this.filter=b}
Ba.prototype.log=function(a,b){this.g.log(a,this.filter(b))};function Ca(a,b){return new Ba(a,b)}function Da(a){return Ca(a,function(a){var c=new Date;return["["+A(""+c.getHours())+":"+A(""+c.getMinutes())+":"+A(""+c.getSeconds())+"]"].concat(Array.prototype.slice.call(a,0))})}function Ea(a){return Ca(a,function(a){a=ya(a);40<a.length&&(a=a.substr(0,37)+"...");return[a]})}
function Fa(a){a=void 0===a?1E4:a;for(var b=[],c=0;31>c;++c)b.push(U(a));a=R(15,"automatic","automatic",b);a.select(14);b=B(e(a),"noh log reel");b.i=a;b.log=function(a,b){Q(this.i,this.i.d)[0].log(a,b);this.i.rotate(-1)};b.Z=function(a){var b=a-this.i.d;this.i.d=a;this.i.rotate(b)};return b}
function Ga(a,b){var c=b||'alert("hello world")',d=B(ka().attr("type","text").attr("size",a).attr("placeholder",c),"noh cmdline"),c=B(x(String.fromCharCode(8629)).attr("title","Press enter to run the command."),"noh cmdline"),f=B(e(d,c).css("display","inline-block"),"noh cmdline");f.r=function(){var a=d.a.val();console.log(a);try{var b=eval(a);void 0!==b&&console.log(b)}catch(c){console.error(c)}d.a.val("")};f.type=function(a){d.a.val(a)};f.focus=function(){d.a.focus()};d.on("keypress",function(a){13==
a.which&&f.r()});c.on("click",function(){f.r()});return f}function X(a,b){for(var c=ra({style:"border: 6px ridge green"},q(a)),d=[],f=0;f<b.length;++f){var k=B(x(b[f]),"noh button").attr("title",'Prepare the "'+b[f]+'" command to run.');k.on("click",function(){window.obj=a;m.type(this.textContent);m.focus()});d.push(k);d.push(p())}var m=Ga(60,"obj.some_method()");return e(h(c),h(m),h(d))}new g("div");new g("div");$(document).ready(function(){var a=$("#noh_tests");if(0!=a.length){var b=e,c=S(t("NOH Simple tests")),d=h("Please check the ",n({href:"noh_doc.html"},"documentation")," first."),f=S(u("TOC")),k=Ha(),m;m=Y;var r=[],v;for(v in m)r.push(fa(S(u({id:"stest_"+v},"stest: ",v))).css("padding","20px"),ga(Ia(m[v])));m=ea(r);b=b(c,d,f,k,m);a[0].appendChild(b.c);window.SyntaxHighlighter&&window.SyntaxHighlighter.all()}});function Ja(a){return e({"class":"noh stest"},arguments)}
function Ia(a){var b=a();return Ja(da(s(w("Source code:"),K("js",a.toString())),s(w("Result:"),Ja(b)),s(w("Result source code (html):"),K("html",b.c.outerHTML||(new XMLSerializer).serializeToString(b.c)))))}function Ha(){var a=Y,b={"class":"noh link",style:"padding: 5px"},c=[],d;for(d in a)a=n(b,d),a.A="#stest_"+d,a.on("click",function(){$(this.m.A)[0].m.scroll()}),c.push(s(a));return da(c)}
var Y={aa:function(){return E()},K:function(){return F()},$:function(){return G()},da:function(){return l({style:"padding:15px; color:white; background-color:white; border:solid 2px white"},"White on white")},B:function(){return H()},B:function(){return H()},M:function(){return e(E(),F(),G())},H:function(){return e(D(I("red")),D(I("green")),D(I("blue")))},V:function(){return e(D(J(5)),D(J(10)),D(J(15)))},L:function(){return e(t("Some h1 text"),ha("Some h2 text"),u("Some h3 text"),w("Some h4 text"),
ia("Some h5 text"),ja("Some h6 text"))},J:function(){return e(S(t("Some h1 text")),S(ha("Some h2 text")),S(u("Some h3 text")),S(w("Some h4 text")),S(ia("Some h5 text")),S(ja("Some h6 text")))},C:function(){return K("js",Y.C.toString())},ba:function(){var a=sa(E(),2E3);return X(a,["obj.wake()","obj.sleep()",'obj.parent.addclass("smooth")','obj.parent.remclass("smooth")'])},F:function(){var a=N(J(4));return B(X(a,["obj.roll(true)","obj.roll(false)","obj.down()"]),"smooth")},R:function(){var a=ta(e({style:"font-style: italic; color: green; font-size: xx-large"},
"BLABLA"),e({style:"color: blue; font-size: xx-large"},"BLEBLE",p(),"BLUBLU"),e({style:"color: red; font-size: xx-large"},"BLIBLI",p(),p(),"BLZBLZ"));a.select(0);return B(X(a,["obj.next()","obj.prev()","obj.select(1)","obj.select(-1)"]),"smooth")},I:function(){var a={style:"color: brown; font-size: x-large; width: 400px;"},a=ua(e(e(a,"bjkalb DETAILS"),e(a,"fjdsklfsd   DETAILS"),e("fjdsklf jksfl dsjlf djksdfl DETAILS")));B(a,"smooth");return X(a,["obj.down()","obj.roll(true)","obj.roll(false)"])},
S:function(){var a=B(e({style:"margin: 10px; color: green; font-size: xx-large"}," overlay BLEBLE",p(),"BLUBLU"),"pretty"),b=B(e({style:"margin: 10px; color: blue; font-size: x-large"}," overlay BLEBLE",p(),"BLUBLU"),"pretty"),c=B(e({style:"margin: 30px; color: red; font-size: large"}," overlay",p(),"BLU"),"pretty"),d=B(L(a,b,c),"right top");d.a.click(function(){d.hide()});a=X(d,'obj.show() obj.hide() obj.show(1) obj.hide(1) obj.show(2) obj.hide(2) obj.parent.addclass("smooth") obj.parent.remclass("smooth") obj[1].addclass("pretty") obj[1].remclass("pretty") obj.remclass("top").addclass("bottom") obj.remclass("bottom").addclass("top")'.split(" "));
B(d.parent,"smooth");return a},T:function(){var a=B(L(B(G(),"pretty"),B(F(),"pretty"),B(E(),"pretty"),B(H(),"pretty")),"top");a.css("left","330px");a.a.click(function(){a.hide()});var b=X(a,'obj.show();obj.hide();obj.show(2);obj.hide(2);obj.parent.addclass("smooth");obj.parent.remclass("smooth");obj[1].addclass("pretty");obj[1].remclass("pretty");obj.remclass("top").addclass("bottom");obj.remclass("bottom").addclass("top");obj.css("left", "30px");obj.css("left", "330px")'.split(";"));B(a.parent,"smooth");
return b},U:function(){var a=B(Fa(),"pretty");window.console=new V(Aa([new W(window.console),Ea(Da(a))]));var b=B(Ga(40),"pretty"),a=L(a,b);B(a,"bottom");a.css("right","10px");b=X(a,'obj.show();obj.hide();obj.show(1);obj.hide(1);obj.parent.addclass("smooth");obj.parent.remclass("smooth");obj.remclass("top").addclass("bottom");obj.remclass("bottom").addclass("top");obj.css("right", "30px");obj.css("right", "230px")'.split(";"));B(a.parent,"smooth");return b}},Ka='obj.rotate(2);obj.rotate(-3);obj.rotation;obj.spin(20);obj.spin(-12, -4, 100);obj.update(2);obj.update(5);obj.parent.addclass("smooth");obj.parent.remclass("smooth");obj.parent.addclass("fast");obj.parent.remclass("fast");obj.parent.addclass("slow");obj.parent.remclass("slow");obj.parent.addclass("very_slow");obj.parent.remclass("very_slow");obj.addclass("fancy");obj.remclass("fancy")'.split(";");
Y.W=function(){var a={style:"padding: 5px; border: solid blue; color: black; font-size: large; width: 400px; background: wheat"},a=R(5,"dynamic","dynamic",e(a,"BLABLA").css("background","green"),e(a,"BLABLA").css("background","blue"),e(a,"BLEBLE",p(),"BLUBLU").css("width","500px"),e(a,"BLEBLE",p(),"BLUBLU").css("width","200px"),e(a,"BLEBLE",p(),"BLUBLU").css("width","220px"),e(a,"BLIBLI",p(),"margin:10px",p(),"BLZBLZ").css("width","270px").css("margin","10px"),e(a,"BLIBLI",p(),"margin:20px",p(),"BLZBLZ").css("width",
"250px").css("margin","20px"),e(a,"BLIBLI",p(),p(),"BLZBLZ").css("width","130px"));a.select(2);var b=X(a,Ka);B(a.parent,"smooth");return b};function Z(a,b){for(var c=[],d={style:"font-family: monospace; margin: 5px; padding: 15px; border: solid black; color: black; font-size: large; width: 100; background: wheat"},f=a;f<=b;++f){for(var k=""+f;3>k.length;)k="0"+k;c.push(e(d,""+k))}return B(B(R(3,"automatic","automatic",c).select(1),"smooth"),"fancy")}
Y.X=function(){var a=Z(1,12),b=X(a,Ka);B(a.parent,"smooth");return b};
Y.Y=function(){function a(a){var b=Z(0,a),c=Z(0,a),d=Z(0,a);a=ra(q(b),q(c),q(d));a.k=function(){d.rotate(-1);0==d.rotation&&(c.rotate(-1),0==c.rotation&&b.rotate(-1))};return a}var b=a(3),c=a(5),d=a(9),f=R(5,"dynamic","dynamic",b,c,d);f.k=function(){b.k();c.k();d.k()};f.stop=function(){this.n&&window.clearInterval(this.n);this.n=void 0};f.start=function(a){f.stop();f.n=window.setInterval(function(){f.k()},a)};var k=X(f,Ka.concat("obj.start(200)","obj.stop()"));B(f.parent,"smooth");window.setTimeout(function(){f.update(3)},
3E3);return k};Y.ca=function(){return e(xa("fjdkl http://www.google.pl google fjsdk ftp://blabal fjdsl http://mareklangiewicz.pl fds fjdsklfds"))};
Y.Q=function(){var a=U(3E3),b=X(a,'obj.log("info", ["dupa info"]);obj.log("warning", ["dupa warning"]);obj.log("error", ["dupa error", "dupa error2", 3, 4, window]);obj.log("info warning", ["dupa info warning"]);noh.log.l2c(obj).install();noh.log.l2c(noh.log.addtime(obj)).install();obj.addclass("pretty");obj.remclass("pretty")'.split(";"));B(a.parent,"smooth");return b};
Y.O=function(){var a=U(1E3),b=U(2E3),c=U(3E3),d=Aa([a,b,c,new W(window.console)]),a=e(a,b,c);a.log=function(a,b){d.log(a,b)};b=X(a,'obj.log("info", ["dupa info"]);obj.log("warning", ["dupa warning"]);obj.log("error", ["dupa error", "dupa error2", 3, 4, window]);obj.log("info warning", ["dupa info warning"]);noh.log.l2c(obj).install();noh.log.l2c(noh.log.addtime(obj)).install()'.split(";"));B(a.parent,"smooth");return b};
Y.P=function(){var a=Fa(),b=X(a,'obj.log("info", ["dupa info"]);obj.log("warning", ["dupa warning"]);obj.log("error", ["dupa error", "dupa error2", 3, 4, window]);obj.log("info warning", ["dupa info warning"]);noh.log.l2c(obj).install();noh.log.l2c(noh.log.addtime(obj)).install();obj.addclass("pretty");obj.remclass("pretty");obj.setlines(5);obj.setlines(9)'.split(";"));B(a.parent,"smooth");return b};Y.N=function(){var a=B(Fa(3E4),"pretty smooth");return X(a,["install_logger(obj)"])};
Y.G=function(){var a=Ga(40);return X(a,['obj.type("2+2")','obj.type("2+2*2")','obj.type("window")',"obj.run()"])};
