noh={na:function(a){a&&(this.message=a)}};noh.na.prototype=Error("Not implemented");noh.Ia=function(a){a&&(this.message=a)};noh.Ia.prototype=new noh.na("Operation not supported");noh.Ya="html head body script meta title link div p span a img br hr em i strong table tr th td thead tbody tfoot colgroup col ul ol li dl dt dd h1 h2 h3 h4 h5 h6 form fieldset input textarea label select option b pre code button kbd".split(" ");noh.body=function(a){return new noh.c("body",arguments)};
noh.link=function(a){return new noh.c("link",arguments)};noh.d=function(a){return new noh.c("div",arguments)};noh.wb=function(a){return new noh.c("p",arguments)};noh.span=function(a){return new noh.c("span",arguments)};noh.b=function(a){return new noh.c("a",arguments)};noh.lb=function(a){return new noh.c("img",arguments)};noh.e=function(a){return new noh.c("br",arguments)};noh.jb=function(a){return new noh.c("hr",arguments)};noh.fb=function(a){return new noh.c("em",arguments)};
noh.kb=function(a){return new noh.c("i",arguments)};noh.Ab=function(a){return new noh.c("strong",arguments)};noh.table=function(a){return new noh.c("table",arguments)};noh.Wa=function(a){return new noh.c("tr",arguments)};noh.Fb=function(a){return new noh.c("th",arguments)};noh.m=function(a){return new noh.c("td",arguments)};noh.Gb=function(a){return new noh.c("thead",arguments)};noh.tbody=function(a){return new noh.c("tbody",arguments)};noh.Eb=function(a){return new noh.c("tfoot",arguments)};
noh.cb=function(a){return new noh.c("colgroup",arguments)};noh.bb=function(a){return new noh.c("col",arguments)};noh.Xa=function(a){return new noh.c("ul",arguments)};noh.sb=function(a){return new noh.c("ol",arguments)};noh.$=function(a){return new noh.c("li",arguments)};noh.La=function(a){return new noh.c("dl",arguments)};noh.Na=function(a){return new noh.c("dt",arguments)};noh.Ja=function(a){return new noh.c("dd",arguments)};noh.ua=function(a){return new noh.c("h1",arguments)};
noh.V=function(a){return new noh.c("h2",arguments)};noh.W=function(a){return new noh.c("h3",arguments)};noh.D=function(a){return new noh.c("h4",arguments)};noh.va=function(a){return new noh.c("h5",arguments)};noh.wa=function(a){return new noh.c("h6",arguments)};noh.form=function(a){return new noh.c("form",arguments)};noh.hb=function(a){return new noh.c("fieldset",arguments)};noh.input=function(a){return new noh.c("input",arguments)};noh.Db=function(a){return new noh.c("textarea",arguments)};
noh.label=function(a){return new noh.c("label",arguments)};noh.select=function(a){return new noh.c("select",arguments)};noh.tb=function(a){return new noh.c("option",arguments)};noh.$a=function(a){return new noh.c("b",arguments)};noh.Va=function(a){return new noh.c("pre",arguments)};noh.code=function(a){return new noh.c("code",arguments)};noh.button=function(a){return new noh.c("button",arguments)};noh.ya=function(a){return new noh.c("kbd",arguments)};noh.text=function(a){return new noh.oa(a)};
noh.p=function(a,b,c){c=c?c:{n:{},g:[]};if(a instanceof noh.r)c.g.push(a);else if("string"===typeof a)c.g.push(noh.text(a));else if(noh.s.Oa(a))for(b=void 0===b?0:b;b<a.length;++b)noh.p(a[b],0,c);else if(a instanceof Object)$.extend(c.n,a);else if(void 0!==a&&null!==a)throw new TypeError("Unknown argument type: "+typeof a+" value: "+String(a));return c};noh.s={};noh.s.push=function(a,b){return b.push.apply(b,a)};noh.s.indexOf=function(a,b){for(var c=0;c<b.length;++c)if(a==b[c])return c;return-1};
noh.s.Za=function(a,b){if(null===b)return null;for(var c={},d=0;d<a.length;++d)c[a[d]]=b[d];return c};noh.s.rb=function(a,b){if(null===b)return null;for(var c=[],d=0;d<a.length;++d)c.push(b[a[d]]);return c};noh.s.Oa=function(a){var b=Object.prototype.hasOwnProperty,c;return null!=a&&(a instanceof jQuery||"number"===typeof(c=a.length)&&(0<=c&&b.call(a,0)&&b.call(a,c-1)||jQuery.isArray(a)))};noh.B={};noh.B.M=function(a,b){a.length>b&&(a=a.substr(0,b-3)+"...");return a};
noh.B.prefix=function(a,b,c){for(;a.length<c;)a=b+a;return a};noh.r=function(){this.length=0;this.a=this.j=this.parent=null};noh.r.prototype.add=function(a){this.j.appendChild(a.j);a.parent=this;Array.prototype.push.call(this,a);return this};noh.oa=function(a){this.text=a;noh.r.call(this);this.j=document.createTextNode(a);this.j.aa=this;this.a=$(this.j)};noh.oa.prototype=new noh.r;
noh.c=function(a,b){this.tag=a;noh.r.call(this);this.j=document.createElement(a);this.j.aa=this;this.a=$(this.j);var c=noh.p(arguments,1),d;for(d in c.n)this.attr(d,c.n[d]);for(d=0;d<c.g.length;++d)this.add(c.g[d])};noh.c.prototype=new noh.r;noh.c.prototype.attr=function(a,b){this.a.attr(a,b);return this};noh.c.prototype.css=function(a,b){this.a.css(a,b);return this};noh.c.prototype.on=function(a,b){this.a.on(a,b);return this};function f(a,b){a.a.addClass(b);return a}
function h(a,b){a.a.removeClass(b);return a}noh.scroll=function(a,b){$("html,body").animate({scrollTop:a},b?b:1E3)};noh.c.prototype.scroll=function(a){noh.scroll(this.a.offset().top,a);return this};noh.l=function(a){var b=noh.p(arguments);return noh.table(b.n,noh.tbody(noh.Wa(b.g)))};noh.Cb=function(a){for(var b=noh.p(arguments),c=[],d=0;d<b.children.length;++d)c.push(j.m(b.g[d]));return noh.l({"class":"noh bar"},b.n,c)};
noh.A=function(a){return noh.d({style:"margin:10px; padding:10px; border:solid 2px"},arguments)};noh.f={};noh.f.da=function(){return noh.span("Simpleeeee! kind of man!").css("padding",10).css("background-color","lightgray").css("border","solid 2px")};noh.f.U=function(){return noh.span("Daaaaa..").css("padding",20).css("background-color","gray").css("border","solid 4px")};
noh.f.P=function(){return noh.span({style:"padding: 25px; font-size:xx-large; color:red; background-color:yellow; border:solid 1px red; border-radius:40px"},":-)")};noh.f.Ga=function(){return noh.span({style:"padding:15px; color:white; background-color:white; border:solid 2px white"},"White on white")};noh.f.O=function(){return noh.span({style:"padding:10px; color:red; background-color:pink; border:solid 2px red"},":*")};noh.f.xa=function(){return noh.d(noh.f.da(),noh.f.U(),noh.f.P())};
noh.f.color=function(a){return noh.span({style:"padding:8px"},"C").css("color",a).css("background-color",a)};noh.f.ca=function(a){for(var b=[],c=0;c<a;++c)b.push(noh.f.color("hsl("+360*c/a+",100%,50%)"));return noh.span(b)};noh.Da=function(a,b){return noh.Va({"class":"brush: "+a+"; toolbar: false"},b)};noh.Q=function(a){return noh.Da("js",a.toString())};
noh.N=function(a){var b=f(noh.d(arguments),"noh overlay");b.show=function(a){a=void 0===a?this:this[a];if(!a.a.hasClass("hidden"))return b;(this.a.hasClass("left")||this.a.hasClass("right"))&&a.css("left","").css("right","");(this.a.hasClass("top")||this.a.hasClass("bottom"))&&a.css("top","").css("bottom","");f(h(a,"hidden"),"visible");return this};b.hide=function(a){a=void 0===a?this:this[a];if(a.a.hasClass("hidden"))return b;var d=$(window).width(),e=$(window).height(),g=a.a.outerWidth(!0),l=a.a.outerHeight(!0),
k=a.a.offset(),m=k.left,k=k.top-$(document).scrollTop(),d=d-m-g,e=e-k-l;this.a.hasClass("left")?a.css("left",""+(-m-g-5)+"px"):this.a.hasClass("right")?a===this?a.css("right",""+(-d-g-5)+"px"):a.css("left",""+(g+d+5)+"px"):this.a.hasClass("top")?a.css("top",""+(-k-l-5)+"px"):this.a.hasClass("bottom")&&(a===this?a.css("bottom",""+(-e-l-5)+"px"):a.css("top",""+(l+e+5)+"px"));f(h(a,"visible"),"hidden");return this};return b};
noh.fa=function(a,b){f(f(a,"noh"),"sleepy");a.Ka=void 0===b?1E3:b;a.Fa=function(){f(h(this,"asleep"),"awake");window.clearTimeout(this.ga);this.ga=window.setTimeout(function(){a.ea()},a.Ka)};a.ea=function(){window.clearTimeout(this.ga);this.ga=void 0;f(h(this,"awake"),"asleep")};a.ea();return a};noh.ja=function(){};noh.ja.prototype.L=function(){};noh.ja.prototype.q=function(){};
noh.G=function(a){var b=f(noh.d(arguments),"noh blind content");noh.c.call(this,"div",b);f(this,"noh blind");this.C=b;this.q(!1);var c=this;this.a.show(function(){c.q(c.L())})};noh.G.prototype=new noh.c("div");noh.G.prototype.L=function(){return this.Ma};
noh.G.prototype.q=function(a){var b=this.a,c=this.C.a,d=c.width(),e=c.height();c.css("clip","rect(0px "+d+"px "+(a?e:0)+"px 0px");a?(h(this.C,"hidden"),f(this.C,"visible")):(h(this.C,"visible"),f(this.C,"hidden"));b.width(d);b.height(a?e:0);this.Ma=a;return this};noh.K=function(a){return new noh.G(arguments)};noh.ka=function(){};noh.ka.prototype.selected=function(){};noh.ka.prototype.select=function(){};
noh.v=function(a){for(var b=noh.p(arguments),c=0;c<b.g.length;++c){var d=noh.K(b.g[c]);b.g[c]=d;d.Ua=c}noh.c.call(this,"div",b.n,b.g);f(this,"noh oneof");this.h=-1};noh.v.prototype=new noh.c("div");noh.v.prototype.selected=function(){return this.h};noh.v.prototype.select=function(a){a instanceof noh.r?a=a.Ua:null===a&&(a=-1);var b=this.length;if(-1>a||a>=b)a=-1;-1!=this.h&&this[this.h].q(!1);-1!=a&&this[a].q(!0);this.h=a;return this};function s(a,b){return a.select(0>b?a.length-1:b%a.length)}
noh.v.prototype.next=function(){return s(this,this.selected()+1)};noh.v.prototype.prev=function(){return s(this,this.selected()-1)};noh.ba=function(a){return new noh.v(arguments)};noh.sa=function(a){var b=f(noh.d(arguments),"noh details content"),c=noh.K(b),b=f(noh.button("details..."),"noh details button").attr("title","show/hide details");b.on("click",function(){c.q(!c.L())});return f(noh.d(noh.d(b),noh.d(c)),"noh details")};
noh.w=function(a,b,c,d){for(var e=noh.p(arguments,3),g=0;g<e.g.length;++g){var l=f(noh.d(e.g[g]),"noh reel element");e.g[g]=l}noh.c.call(this,"div",e.n,e.g);f(this,"noh reel");this.k=a;this.rotation=0;this.width=b;this.height=c;u(this);var k=this;this.a.show(function(){k.update()});this.h=-1};noh.w.prototype=new noh.c("div");noh.w.prototype.selected=function(){return this.h};
noh.w.prototype.select=function(a){if(-1>a||a>=this.length)a=-1;if(this.h==a)return this;-1!=this.h&&h(v(this,this.h),"selected");-1!=a&&f(v(this,a),"selected");this.h=a;return this};
function u(a){var b=0;if("automatic"==a.width)for(var c=0;c<a.length;++c)esize=a[c].a.width(),esize>b&&(b=esize);else if("dynamic"==a.width)for(c=0;c<a.k;++c)esize=v(a,c).a.width(),esize>b&&(b=esize);else b=a.width;a.css("min-width",b).css("max-width",b).css("width",b);b=0;if("automatic"==a.height){for(c=0;c<a.length;++c)esize=a[c].a.height(),esize>b&&(b=esize);b*=a.k}else if("dynamic"==a.height){for(c=0;c<a.k;++c)esize=v(a,c).a.height(),esize>b&&(b=esize);b*=a.k}else b=a.height;a.css("min-height",
b).css("max-height",b).css("height",b);a.ta=b}function w(a,b){for(;0>b;)b+=a.length;for(;b>=a.length;)b-=a.length;return b}function v(a,b){return a[w(a,b-a.rotation)]}
noh.w.prototype.update=function(a){void 0!==a&&(this.k=a);u(this);for(a=0;a<this.length;++a){var b=v(this,a);h(b,"selected");a<this.k?(f(h(b,"hidden"),"visible"),b.css("top",""+a*this.ta/this.k+"px")):(f(h(b,"visible"),"hidden"),b.css("top",""+(this.length-a-1)*this.ta/(this.length-this.k)+"px"))}-1!=this.h&&f(v(this,this.h),"selected");return this};noh.w.prototype.rotate=function(a){this.rotation=w(this,this.rotation+a);return this.update()};
function x(a,b,c,d){a.X?console.error("The reel is already spinning!"):(c&&(b+=Math.round(Math.random()*c)),a.X=window.setInterval(function(){0==b?(window.clearInterval(a.X),a.X=void 0):0<b?(a.rotate(1),--b):(a.rotate(-1),++b)},d?d:200))}noh.i=function(a,b,c,d){var e=noh.p(arguments,3);return new noh.w(a,b,c,e.n,e.g)};noh.o=function(a){f(a,"fancy");if(-1!=noh.s.indexOf(a.tag,["h1","h2","h3","h4"]))a.on("click",function(){this.aa.scroll()});return a};
noh.Ea=function(a){var b=/(https?|ftp):\/\//;a=a.split(/\s+/).map(function(a){return b.test(a)?noh.b({href:a,target:"_blank"},a):" "+a+" "});return noh.ya(a)};noh.log={};noh.log.ra=function(a){var b="";0<a.length&&(b+=a[0]);for(var c=1;c<a.length;++c)b=b+" "+a[c].toString();return b};noh.log.Ha=function(){};noh.log.Ha.prototype.log=function(){};noh.log.S=function(){noh.c.call(this,"div");f(this,"noh log little")};noh.log.S.prototype=new noh.c("div");
noh.log.S.prototype.log=function(a,b){if(this.length){var c=Array.prototype.pop.call(this);c.parent=null;this.j.removeChild(c.j)}c=f(f(noh.Ea(noh.log.ra(b)),"noh log element"),a);this.add(c)};noh.log.Pa=function(){return new noh.log.S};noh.log.F=function(a){var b=noh.log.Pa();a=noh.fa(b,a);a.Qa=a.log;a.log=function(a,b){this.Qa(a,b);this.Fa()};return a};noh.log.H=function(){};noh.log.H.prototype.log=function(){};noh.log.H.prototype.info=function(){};noh.log.H.prototype.warn=function(){};
noh.log.H.prototype.error=function(){};noh.log.u=function(a){this.t=a};noh.log.u.prototype.log=function(a){this.t.log("info",arguments)};noh.log.u.prototype.info=function(a){this.t.log("info",arguments)};noh.log.u.prototype.warn=function(a){this.t.log("warning",arguments)};noh.log.u.prototype.error=function(a){this.t.log("error",arguments)};noh.log.u.prototype.debug=function(a){this.t.log("debug",arguments)};noh.log.Z=function(a){return new noh.log.u(a)};noh.log.ha=function(a){this.console=a};
noh.log.ha.prototype.log=function(a,b){/error/.test(a)?this.console.error.apply(this.console,b):/warning/.test(a)?this.console.warn.apply(this.console,b):/debug/.test(a)&&this.console.debug instanceof Function?this.console.debug.apply(this.console,b):this.console.info.apply(this.console,b)};noh.log.qa=function(){return new noh.log.ha(window.console)};noh.log.ma=function(a){this.za=a};noh.log.ma.prototype.log=function(a,b){for(var c=0;c<this.za.length;++c)this.za[c].log(a,b)};noh.log.Aa=function(a){return new noh.log.ma(a)};
noh.log.ia=function(a,b){this.t=a;this.filter=b};noh.log.ia.prototype.log=function(a,b){this.t.log(a,this.filter(b))};noh.log.filter=function(a,b){return new noh.log.ia(a,b)};noh.log.pa=function(a){return noh.log.filter(a,function(a){var c=new Date;return["["+noh.B.prefix(""+c.getHours(),"0",2)+":"+noh.B.prefix(""+c.getMinutes(),"0",2)+":"+noh.B.prefix(""+c.getSeconds(),"0",2)+"]"].concat(Array.prototype.slice.call(a,0))})};
noh.log.M=function(a,b){return noh.log.filter(a,function(a){return[noh.B.M(noh.log.ra(a),b)]})};noh.log.i=function(a,b){for(var c=2*a+1,d=void 0===b?1E4:b,e=[],g=0;g<c;++g)e.push(noh.log.F(d));c=noh.i(a,"automatic","automatic",e);c.select(a-1);logger=f(noh.d(c),"noh log reel");logger.i=c;logger.log=function(a,b){v(this.i,this.i.k)[0].log(a,b);this.i.rotate(-1)};logger.Ca=function(a){var b=a-this.i.k;this.i.k=a;this.i.rotate(b)};return logger};
noh.T=function(a){var b=f(noh.input().attr("type","text").attr("size",a).attr("placeholder",'alert("hello world")'),"noh cmdline");a=f(noh.button(String.fromCharCode(8629)).attr("title","Press enter to run the command."),"noh cmdline");var c=f(noh.d(b,a).css("display","inline-block"),"noh cmdline");c.Ba=function(){var a=b.a.val();console.log(a);try{var c=eval(a);void 0!==c&&console.log(c)}catch(g){console.error(g)}b.a.val("")};b.on("keypress",function(a){13==a.which&&c.Ba()});a.on("click",function(){c.Ba()});
return c};noh.la=function(){};noh.la.prototype.selected=function(){};noh.la.prototype.toggle=function(){};noh.J=function(a){noh.c.call(this,"div",{"class":"noh menu item"},a);this.on("click",function(){this.aa.toggle();return!1})};noh.J.prototype=new noh.c("div");noh.J.prototype.toggle=function(){this.a.toggleClass("selected")};noh.J.prototype.selected=function(){return this.a.hasClass("selected")};noh.qb=function(a){return new noh.J(a)};
noh.ab=function(a,b){var c=noh.ba(b),d=noh.d(noh.d(a),noh.d(c));a.R=a.toggle;a.toggle=function(){d.toggle()};d.toggle=function(){a.R();c.select(this.selected()?0:-1)};d.selected=function(){return a.selected()};return d};noh.I=function(a){var b=noh.p(arguments);noh.c.call(this,"div",b.n,b.g);this.Y=b.g;for(b=0;b<this.Y.length;++b){var c=this.items[b];c.selected()&&c.toggle();c.Ta=this;c.Sa=b;c.R=c.toggle;c.toggle=function(){this.Ta.select(this.selected()?-1:this.Sa)}}this.h=-1};noh.I.prototype=new noh.c("div");
noh.I.prototype.selected=function(){return this.h};noh.I.prototype.select=function(a){-1!=this.h&&this.Y[selected_].R();this.h=a;-1!=a&&this.Y[a].R()};noh.Ra=function(a){return new noh.I(arguments)};noh.Bb=function(a,b){var c=bigmenuitem(a,b);c.Ra=b;return c};$(document).ready(function(){var a=$("#noh_tests");if(0!=a.length){var b=noh.d(noh.o(noh.V("Simple tests")),y());a[0].appendChild(b.j);SyntaxHighlighter.all()}});function z(a){return noh.d({"class":"noh stest"},arguments)}function A(a){var b=a();return z(noh.Xa(noh.$(noh.D("Source code:"),z(noh.Q(a))),noh.$(noh.D("Result:"),z(b)),noh.$(noh.D("Result source code (html):"),z(noh.Da("html",b.j.outerHTML||(new XMLSerializer).serializeToString(b.j))))))}
function y(){var a=B,b=[],c;for(c in a)b.push(noh.Na(noh.o(noh.W("stest: ",c))).css("padding","20px"),noh.Ja(A(a[c])));return noh.La(b)}
var B={da:function(){return noh.f.da()},U:function(){return noh.f.U()},P:function(){return noh.f.P()},Ga:function(){return noh.f.Ga()},O:function(){return noh.f.O()},O:function(){return noh.f.O()},xa:function(){return noh.f.xa()},eb:function(){return noh.d(noh.A(noh.f.color("red")),noh.A(noh.f.color("green")),noh.A(noh.f.color("blue")))},xb:function(){return noh.d(noh.A(noh.f.ca(5)),noh.A(noh.f.ca(10)),noh.A(noh.f.ca(15)))},ib:function(){return noh.d(noh.ua("Some h1 text"),noh.V("Some h2 text"),noh.W("Some h3 text"),
noh.D("Some h4 text"),noh.va("Some h5 text"),noh.wa("Some h6 text"))},gb:function(){return noh.d(noh.o(noh.ua("Some h1 text")),noh.o(noh.V("Some h2 text")),noh.o(noh.W("Some h3 text")),noh.o(noh.D("Some h4 text")),noh.o(noh.va("Some h5 text")),noh.o(noh.wa("Some h6 text")))},Q:function(){return noh.Q(B.Q)},N:function(){var a=f(noh.d({style:"margin: 10px; color: green; font-size: xx-large"}," overlay BLEBLE",noh.e(),"BLUBLU"),"pretty"),b=f(noh.d({style:"margin: 10px; color: blue; font-size: x-large"},
" overlay BLEBLE",noh.e(),"BLUBLU"),"pretty"),c=f(noh.d({style:"margin: 30px; color: red; font-size: large"}," overlay",noh.e(),"BLU"),"pretty"),d=f(noh.N(a,b,c),"left top");d.a.click(function(){d.hide()});var e={"class":"noh link",style:"padding: 5px"},a=noh.b(e,"overlay.show()"),b=noh.b(e,"overlay.hide()"),c=noh.b(e,"overlay.show(1)"),g=noh.b(e,"overlay.hide(1)"),l=noh.b(e,"overlay.show(2)"),k=noh.b(e,"overlay.hide(2)"),m=noh.b(e,'overlay.parent.addclass("smooth")'),n=noh.b(e,'overlay.parent.remclass("smooth")'),
p=noh.b(e,'overlay[1].addclass("pretty")'),q=noh.b(e,'overlay[1].remclass("pretty")'),r=noh.b(e,'overlay.remclass("top").addclass("bottom")'),e=noh.b(e,'overlay.remclass("bottom").addclass("top")');a.a.click(function(){d.show()});b.a.click(function(){d.hide()});c.a.click(function(){d.show(1)});g.a.click(function(){d.hide(1)});l.a.click(function(){d.show(2)});k.a.click(function(){d.hide(2)});m.a.click(function(){f(d.parent,"smooth")});n.a.click(function(){h(d.parent,"smooth")});p.a.click(function(){f(d[1],
"pretty")});q.a.click(function(){h(d[1],"pretty")});r.a.click(function(){f(h(d,"top"),"bottom")});e.a.click(function(){f(h(d,"bottom"),"top")});return noh.d(a,b,noh.e(),c,g,noh.e(),l,k,noh.e(),m,n,noh.e(),p,q,noh.e(),r,e,noh.l({style:"border: 6px ridge green"},noh.m(d)))},ub:function(){var a=f(noh.d({style:"margin: 10px; color: green; font-size: xx-large"}," overlay BLEBLE",noh.e(),"BLUBLU"),"pretty"),b=f(noh.d({style:"margin: 10px; color: blue; font-size: x-large"}," overlay BLEBLE",noh.e(),"BLUBLU"),
"pretty"),c=f(noh.d({style:"margin: 30px; color: red; font-size: large"}," overlay",noh.e(),"BLU"),"pretty"),d=f(noh.N(a,b,f(noh.f.P(),"pretty"),c),"top");d.css("right","10px");d.a.click(function(){d.hide()});var e={"class":"noh link",style:"padding: 5px"},a=noh.b(e,"overlay.show()"),b=noh.b(e,"overlay.hide()"),c=noh.b(e,"overlay.show(1)"),g=noh.b(e,"overlay.hide(1)"),l=noh.b(e,"overlay.show(2)"),k=noh.b(e,"overlay.hide(2)"),m=noh.b(e,'overlay.parent.addclass("smooth")'),n=noh.b(e,'overlay.parent.remclass("smooth")'),
p=noh.b(e,'overlay.remclass("top").addclass("bottom")'),q=noh.b(e,'overlay.remclass("bottom").addclass("top")'),r=noh.b(e,'overlay.css("right", "30px")'),t=noh.b(e,'overlay.css("right", "130px")'),e=noh.b(e,'overlay.css("right", "230px")');a.a.click(function(){d.show()});b.a.click(function(){d.hide()});c.a.click(function(){d.show(1)});g.a.click(function(){d.hide(1)});l.a.click(function(){d.show(2)});k.a.click(function(){d.hide(2)});m.a.click(function(){f(d.parent,"smooth")});n.a.click(function(){h(d.parent,
"smooth")});p.a.click(function(){f(h(d,"top"),"bottom")});q.a.click(function(){f(h(d,"bottom"),"top")});r.a.click(function(){d.css("right","30px")});t.a.click(function(){d.css("right","130px")});e.a.click(function(){d.css("right","230px")});return noh.d(a,b,noh.e(),c,g,noh.e(),l,k,noh.e(),m,n,noh.e(),p,q,noh.e(),r,t,e,noh.l({style:"border: 6px ridge green"},noh.m(d)))},vb:function(){var a=f(noh.log.i(15),"pretty");C(a);var b=f(noh.T(40),"pretty"),c=noh.N(a,b);f(c,"bottom");f(c,"smooth");c.css("right",
"10px");var d={"class":"noh link",style:"padding: 5px"},a=noh.b(d,"overlay.show()"),b=noh.b(d,"overlay.hide()"),e=noh.b(d,"overlay.show(1)"),g=noh.b(d,"overlay.hide(1)"),l=noh.b(d,"overlay.show(2)"),k=noh.b(d,"overlay.hide(2)"),m=noh.b(d,'overlay.parent.addclass("smooth")'),n=noh.b(d,'overlay.parent.remclass("smooth")'),p=noh.b(d,'overlay.remclass("top").addclass("bottom")'),q=noh.b(d,'overlay.remclass("bottom").addclass("top")'),r=noh.b(d,'overlay.css("right", "30px")'),t=noh.b(d,'overlay.css("right", "130px")'),
d=noh.b(d,'overlay.css("right", "230px")');a.a.click(function(){c.show()});b.a.click(function(){c.hide()});e.a.click(function(){c.show(1)});g.a.click(function(){c.hide(1)});l.a.click(function(){c.show(2)});k.a.click(function(){c.hide(2)});m.a.click(function(){f(c.parent,"smooth")});n.a.click(function(){h(c.parent,"smooth")});p.a.click(function(){f(h(c,"top"),"bottom")});q.a.click(function(){f(h(c,"bottom"),"top")});r.a.click(function(){c.css("right","30px")});t.a.click(function(){c.css("right","130px")});
d.a.click(function(){c.css("right","230px")});return noh.d(a,b,noh.e(),e,g,noh.e(),l,k,noh.e(),m,n,noh.e(),p,q,noh.e(),r,t,d,noh.l({style:"border: 6px ridge green"},noh.m(c)))},fa:function(){var a=noh.d({style:"color: green; font-size: xx-large"}," sleepy BLEBLE",noh.e(),"BLUBLU"),b=noh.fa(a,2E3),c={"class":"noh link",style:"padding: 5px"},a=noh.b(c,"sleepy.wake()"),d=noh.b(c,"sleepy.sleep()"),e=noh.b(c,'sleepy.parent.addclass("smooth")'),c=noh.b(c,'sleepy.parent.remclass("smooth")');a.a.click(function(){b.Fa()});
d.a.click(function(){b.ea()});e.a.click(function(){f(b.parent,"smooth")});c.a.click(function(){h(b.parent,"smooth")});return noh.d(a,d,e,c,noh.l({style:"border: 6px ridge green"},noh.m(b)))},K:function(){var a=noh.K(noh.d({style:"color: blue; font-size: xx-large"},"blind BLEBLE",noh.e(),"BLUBLU")),b={"class":"noh link",style:"padding: 5px"},c=noh.b(b,"blind.roll(true)"),d=noh.b(b,"blind.roll(false)"),b=noh.b(b,"alert(blind.down())");c.a.click(function(){a.q(!0)});d.a.click(function(){a.q(!1)});b.a.click(function(){alert(a.L())});
return noh.d(c,d,b,noh.l({style:"border: 6px ridge green"},noh.m(a)))},ba:function(){var a=noh.ba(noh.d({style:"font-style: italic; color: green; font-size: xx-large"},"BLABLA"),noh.d({style:"color: blue; font-size: xx-large"},"BLEBLE",noh.e(),"BLUBLU"),noh.d({style:"color: red; font-size: xx-large"},"BLIBLI",noh.e(),noh.e(),"BLZBLZ"));a.select(0);var b={"class":"noh link",style:"padding: 5px"},c=noh.b(b,"oneof.next()"),d=noh.b(b,"oneof.prev()"),e=noh.b(b,"oneof.select(1)"),b=noh.b(b,"oneof.select(-1)");
c.a.click(function(){a.next()});d.a.click(function(){a.prev()});e.a.click(function(){a.select(1)});b.a.click(function(){a.select(-1)});return noh.d(c,d,e,b,noh.l({style:"border: 6px ridge green"},noh.m(a)))},sa:function(){var a={style:"color: brown; font-size: x-large; width: 400px;"};return noh.d(noh.span(a,"BASIC INFO"),noh.sa(noh.d(noh.d(a,"bjkalb DETAILS"),noh.d(a,"fjdsklfsd   DETAILS"),noh.d("fjdsklf jksfl dsjlf djksdfl DETAILS"))))}};
function N(a){var b={"class":"noh link",style:"padding: 5px"},c=noh.b(b,'reel.parent.addclass("smooth")'),d=noh.b(b,'reel.parent.remclass("smooth")'),e=noh.b(b,'reel.parent.addclass("fast")'),g=noh.b(b,'reel.parent.remclass("fast")'),l=noh.b(b,'reel.parent.addclass("slow")'),k=noh.b(b,'reel.parent.remclass("slow")'),m=noh.b(b,'reel.parent.addclass("very_slow")'),n=noh.b(b,'reel.parent.remclass("very_slow")'),p=noh.b(b,'reel.addclass("fancy")'),q=noh.b(b,'reel.remclass("fancy")'),r=noh.b(b,"reel.rotate(1)"),
t=noh.b(b,"reel.rotate(2)"),D=noh.b(b,"reel.rotate(3)"),E=noh.b(b,"reel.rotate(-1)"),F=noh.b(b,"reel.rotate(-2)"),G=noh.b(b,"reel.rotate(-3)"),H=noh.b(b,"reel.spin(20)"),I=noh.b(b,"reel.spin(-12, -4, 100)"),J=noh.b(b,"reel.update(1)"),K=noh.b(b,"reel.update(2)"),L=noh.b(b,"reel.update(3)"),M=noh.b(b,"reel.update(5)"),b=noh.b(b,"reel.update(7)");c.a.click(function(){f(a.parent,"smooth")});d.a.click(function(){h(a.parent,"smooth")});e.a.click(function(){f(a.parent,"fast")});g.a.click(function(){h(a.parent,
"fast")});l.a.click(function(){f(a.parent,"slow")});k.a.click(function(){h(a.parent,"slow")});m.a.click(function(){f(a.parent,"very_slow")});n.a.click(function(){h(a.parent,"very_slow")});p.a.click(function(){f(a,"fancy")});q.a.click(function(){h(a,"fancy")});r.a.click(function(){a.rotate(1)});t.a.click(function(){a.rotate(2)});D.a.click(function(){a.rotate(3)});E.a.click(function(){a.rotate(-1)});F.a.click(function(){a.rotate(-2)});G.a.click(function(){a.rotate(-3)});H.a.click(function(){x(a,20)});
I.a.click(function(){x(a,-12,-4,100)});J.a.click(function(){a.update(1)});K.a.click(function(){a.update(2)});L.a.click(function(){a.update(3)});M.a.click(function(){a.update(5)});b.a.click(function(){a.update(7)});return noh.d(c,d,noh.e(),e,g,noh.e(),l,k,noh.e(),m,n,noh.e(),p,q,noh.e(),r,t,D,E,F,G,noh.e(),H,I,noh.e(),J,K,L,M,b,noh.d(noh.l(noh.m({style:"border: 6px ridge green"},a))))}
B.yb=function(){var a={style:"padding: 5px; border: solid blue; color: black; font-size: large; width: 400px; background: wheat"},a=noh.i(5,"dynamic","dynamic",noh.d(a,"BLABLA").css("background","green"),noh.d(a,"BLABLA").css("background","blue"),noh.d(a,"BLEBLE",noh.e(),"BLUBLU").css("width","500px"),noh.d(a,"BLEBLE",noh.e(),"BLUBLU").css("width","200px"),noh.d(a,"BLEBLE",noh.e(),"BLUBLU").css("width","220px"),noh.d(a,"BLIBLI",noh.e(),"margin:10px",noh.e(),"BLZBLZ").css("width","270px").css("margin",
"10px"),noh.d(a,"BLIBLI",noh.e(),"margin:20px",noh.e(),"BLZBLZ").css("width","250px").css("margin","20px"),noh.d(a,"BLIBLI",noh.e(),noh.e(),"BLZBLZ").css("width","130px"));a.select(2);return N(a)};
B.zb=function(){var a;a=[];for(var b={style:"font-family: monospace; margin: 5px; padding: 15px; border: solid black; color: black; font-size: large; width: 100; background: wheat"},c=1;12>=c;++c){for(var d=""+c;3>d.length;)d="0"+d;a.push(noh.d(b,""+d))}a=f(f(noh.i(3,"automatic","automatic",a).select(1),"smooth"),"fancy");return N(a)};B.ya=function(){return noh.d(noh.Ea("fjdkl http://www.google.pl google fjsdk ftp://blabal fjdsl http://mareklangiewicz.pl fds fjdsklfds"))};
function O(a){var b={"class":"noh link",style:"padding: 5px"},c=noh.b(b,'logger.log("info", ["dupa info"])'),d=noh.b(b,'logger.log("warning", ["dupa warning"])'),e=noh.b(b,'logger.log("error", ["dupa error", "dupa error2", 3, 4, window])'),g=noh.b(b,'logger.log("info warning", ["dupa info warning"])'),l=noh.b(b,"noh.log.l2c(logger).install()"),k=noh.b(b,"noh.log.l2c(noh.log.addtime(logger)).install()"),m=noh.b(b,'logger.parent.addclass("smooth")'),n=noh.b(b,'logger.parent.remclass("smooth")'),p=noh.b(b,
'logger.addclass("pretty")'),q=noh.b(b,'logger.remclass("pretty")'),r=noh.b(b,"logger.setlines(5)"),b=noh.b(b,"logger.setlines(9)");c.a.click(function(){a.log("info",["dupa info"])});d.a.click(function(){a.log("warning",["dupa warning"])});e.a.click(function(){a.log("error",["dupa error","dupa error2",3,4,window])});g.a.click(function(){a.log("info warning",["dupa info warning"])});l.a.click(function(){window.console=noh.log.Z(a)});k.a.click(function(){var b=noh.log.Z(noh.log.M(noh.log.pa(a),20));
window.console=b});m.a.click(function(){f(a.parent,"smooth")});n.a.click(function(){h(a.parent,"smooth")});p.a.click(function(){f(a,"pretty")});q.a.click(function(){h(a,"pretty")});r.a.click(function(){a.Ca(5)});b.a.click(function(){a.Ca(9)});return noh.d(c,noh.e(),d,noh.e(),e,noh.e(),g,noh.e(),m,n,noh.e(),p,q,noh.e(),l,noh.e(),k,noh.e(),r,b,noh.e(),noh.l({style:"border: 6px ridge green"},noh.m(a)))}B.pb=function(){var a=noh.log.F(3E3);return O(a)};
B.nb=function(){var a=noh.log.F(1E3),b=noh.log.F(2E3),c=noh.log.F(3E3),d=noh.log.Aa([a,b,c,noh.log.qa()]),a=noh.d(a,b,c);a.log=function(a,b){d.log(a,b)};return O(a)};B.ob=function(){var a=noh.log.i(15);return O(a)};function C(a){a=noh.log.Z(noh.log.Aa([noh.log.qa(),noh.log.M(noh.log.pa(a),40)]));window.console=a}
B.mb=function(){var a=noh.b({"class":"noh link",style:"padding: 5px"},"install_logger(logger)"),b=f(noh.log.i(15,3E4),"pretty smooth");a.a.click(function(){C(b);console.log("Welcome!")});return noh.d(a,noh.l({style:"border: 6px ridge green"},noh.m(b)))};B.T=function(){return noh.T(40)};
