noh={NotImplementedError:function(a){a&&(this.message=a)}};noh.NotImplementedError.prototype=Error("Not implemented");noh.NotSupportedError=function(a){a&&(this.message=a)};noh.NotSupportedError.prototype=new noh.NotImplementedError("Operation not supported");noh.TAGS="html head body script meta title link div p span a img br hr em i strong table tr th td thead tbody tfoot colgroup col ul ol li dl dt dd h1 h2 h3 h4 h5 h6 form fieldset input textarea label select option b pre code button kbd".split(" ");
noh.body=function(a){return new noh.Element("body",arguments)};noh.link=function(a){return new noh.Element("link",arguments)};noh.div=function(a){return new noh.Element("div",arguments)};noh.p=function(a){return new noh.Element("p",arguments)};noh.span=function(a){return new noh.Element("span",arguments)};noh.a=function(a){return new noh.Element("a",arguments)};noh.img=function(a){return new noh.Element("img",arguments)};noh.br=function(a){return new noh.Element("br",arguments)};
noh.hr=function(a){return new noh.Element("hr",arguments)};noh.em=function(a){return new noh.Element("em",arguments)};noh.i=function(a){return new noh.Element("i",arguments)};noh.strong=function(a){return new noh.Element("strong",arguments)};noh.table=function(a){return new noh.Element("table",arguments)};noh.tr=function(a){return new noh.Element("tr",arguments)};noh.th=function(a){return new noh.Element("th",arguments)};noh.td=function(a){return new noh.Element("td",arguments)};
noh.thead=function(a){return new noh.Element("thead",arguments)};noh.tbody=function(a){return new noh.Element("tbody",arguments)};noh.tfoot=function(a){return new noh.Element("tfoot",arguments)};noh.colgroup=function(a){return new noh.Element("colgroup",arguments)};noh.col=function(a){return new noh.Element("col",arguments)};noh.ul=function(a){return new noh.Element("ul",arguments)};noh.ol=function(a){return new noh.Element("ol",arguments)};noh.li=function(a){return new noh.Element("li",arguments)};
noh.dl=function(a){return new noh.Element("dl",arguments)};noh.dt=function(a){return new noh.Element("dt",arguments)};noh.dd=function(a){return new noh.Element("dd",arguments)};noh.h1=function(a){return new noh.Element("h1",arguments)};noh.h2=function(a){return new noh.Element("h2",arguments)};noh.h3=function(a){return new noh.Element("h3",arguments)};noh.h4=function(a){return new noh.Element("h4",arguments)};noh.h5=function(a){return new noh.Element("h5",arguments)};
noh.h6=function(a){return new noh.Element("h6",arguments)};noh.form=function(a){return new noh.Element("form",arguments)};noh.fieldset=function(a){return new noh.Element("fieldset",arguments)};noh.input=function(a){return new noh.Element("input",arguments)};noh.textarea=function(a){return new noh.Element("textarea",arguments)};noh.label=function(a){return new noh.Element("label",arguments)};noh.select=function(a){return new noh.Element("select",arguments)};
noh.option=function(a){return new noh.Element("option",arguments)};noh.b=function(a){return new noh.Element("b",arguments)};noh.pre=function(a){return new noh.Element("pre",arguments)};noh.code=function(a){return new noh.Element("code",arguments)};noh.button=function(a){return new noh.Element("button",arguments)};noh.kbd=function(a){return new noh.Element("kbd",arguments)};noh.text=function(a){return new noh.Text(a)};
noh.organize=function(a,b,c){c=c?c:{attrs:{},nodes:[]};if(a instanceof noh.Node)c.nodes.push(a);else if("string"===typeof a)c.nodes.push(noh.text(a));else if(noh.arr.isArrayLike(a))for(b=void 0===b?0:b;b<a.length;++b)noh.organize(a[b],0,c);else if(a instanceof Object)$.extend(c.attrs,a);else if(void 0!==a&&null!==a)throw new TypeError("Unknown argument type: "+typeof a+" value: "+String(a));return c};noh.arr={};noh.arr.push=function(a,b){return b.push.apply(b,a)};
noh.arr.indexOf=function(a,b){for(var c=0;c<b.length;++c)if(a==b[c])return c;return-1};noh.arr.arr2obj=function(a,b){if(null===b)return null;for(var c={},d=0;d<a.length;++d)c[a[d]]=b[d];return c};noh.arr.obj2arr=function(a,b){if(null===b)return null;for(var c=[],d=0;d<a.length;++d)c.push(b[a[d]]);return c};noh.arr.isArrayLike=function(a){var b=Object.prototype.hasOwnProperty,c;return null!=a&&(a instanceof jQuery||"number"===typeof(c=a.length)&&(0<=c&&b.call(a,0)&&b.call(a,c-1)||jQuery.isArray(a)))};
noh.str={};noh.str.limitlen=function(a,b){a.length>b&&(a=a.substr(0,b-3)+"...");return a};noh.str.prefix=function(a,b,c){for(;a.length<c;)a=b+a;return a};noh.Node=function(){this.length=0;this.$=this.dom=this.parent=null};noh.Node.prototype.add=function(a){a.attachToDOM(this.dom);a.parent=this;Array.prototype.push.call(this,a);return this};noh.Node.prototype.rem=function(){var a=Array.prototype.pop.call(this);a.parent=null;a.detachFromDOM(this.dom);return this};
noh.Node.prototype.splice=function(){throw new NotSupportedError;};noh.Node.prototype.attachToDOM=function(a){a.appendChild(this.dom);return this};noh.Node.prototype.detachFromDOM=function(a){a.removeChild(this.dom);return this};noh.Text=function(a){this.text=a;noh.Node.call(this);this.dom=document.createTextNode(a);this.dom.noh=this;this.$=$(this.dom)};noh.Text.prototype=new noh.Node;
noh.Element=function(a,b){this.tag=a;noh.Node.call(this);this.dom=document.createElement(a);this.dom.noh=this;this.$=$(this.dom);var c=noh.organize(arguments,1),d;for(d in c.attrs)this.attr(d,c.attrs[d]);for(d=0;d<c.nodes.length;++d)this.add(c.nodes[d])};noh.Element.prototype=new noh.Node;noh.Element.prototype.attr=function(a,b){this.$.attr(a,b);return this};noh.Element.prototype.css=function(a,b){this.$.css(a,b);return this};noh.Element.prototype.on=function(a,b){this.$.on(a,b);return this};
noh.Element.prototype.addclass=function(a){this.$.addClass(a);return this};noh.Element.prototype.hasclass=function(a){return this.$.hasClass(a)};noh.Element.prototype.toggleclass=function(a){this.$.toggleClass(a);return this};noh.Element.prototype.remclass=function(a){this.$.removeClass(a);return this};noh.scroll=function(a,b){$("html,body").animate({scrollTop:a},b?b:1E3)};noh.Element.prototype.scroll=function(a){noh.scroll(this.$.offset().top,a);return this};
noh.table1r=function(a){var b=noh.organize(arguments);return noh.table(b.attrs,noh.tbody(noh.tr(b.nodes)))};noh.tablebar=function(a){for(var b=noh.organize(arguments),c=[],d=0;d<b.children.length;++d)c.push(j.td(b.nodes[d]));return noh.table1r({"class":"noh bar"},b.attrs,c)};noh.sdiv=function(a){return noh.div({style:"margin:10px; padding:10px; border:solid 2px"},arguments)};noh.ex={};
noh.ex.simple=function(){return noh.span("Simpleeeee! kind of man!").css("padding",10).css("background-color","lightgray").css("border","solid 2px")};noh.ex.goofy=function(){return noh.span("Daaaaa..").css("padding",20).css("background-color","gray").css("border","solid 4px")};noh.ex.silly=function(){return noh.span({style:"padding: 25px; font-size:xx-large; color:red; background-color:yellow; border:solid 1px red; border-radius:40px"},":-)")};
noh.ex.whitey=function(){return noh.span({style:"padding:15px; color:white; background-color:white; border:solid 2px white"},"White on white")};noh.ex.shiny=function(){return noh.span({style:"padding:10px; color:red; background-color:pink; border:solid 2px red"},":*")};noh.ex.idiots=function(){return noh.div(noh.ex.simple(),noh.ex.goofy(),noh.ex.silly())};noh.ex.color=function(a){return noh.span({style:"padding:8px"},"C").css("color",a).css("background-color",a)};
noh.ex.rainbow=function(a){for(var b=[],c=0;c<a;++c)b.push(noh.ex.color("hsl("+360*c/a+",100%,50%)"));return noh.span(b)};noh.syntaxhl=function(a,b){return noh.pre({"class":"brush: "+a+"; toolbar: false"},b)};noh.srccode=function(a){return noh.syntaxhl("js",a.toString())};
noh.overlay=function(a){var b=noh.div(arguments).addclass("noh overlay");b.show=function(a){a=void 0===a?this:this[a];if(!a.hasclass("hidden"))return b;(this.hasclass("left")||this.hasclass("right"))&&a.css("left","").css("right","");(this.hasclass("top")||this.hasclass("bottom"))&&a.css("top","").css("bottom","");a.remclass("hidden").addclass("visible");return this};b.hide=function(a){a=void 0===a?this:this[a];if(a.hasclass("hidden"))return b;var d=$(window).width(),e=$(window).height(),f=a.$.outerWidth(!0),
h=a.$.outerHeight(!0),g=a.$.offset(),k=g.left,g=g.top-$(document).scrollTop(),d=d-k-f,e=e-g-h;this.hasclass("left")?a.css("left",""+(-k-f-5)+"px"):this.hasclass("right")?a===this?a.css("right",""+(-d-f-5)+"px"):a.css("left",""+(f+d+5)+"px"):this.hasclass("top")?a.css("top",""+(-g-h-5)+"px"):this.hasclass("bottom")&&(a===this?a.css("bottom",""+(-e-h-5)+"px"):a.css("top",""+(h+e+5)+"px"));a.remclass("visible").addclass("hidden");return this};return b};
noh.sleepy=function(a,b){a.addclass("noh").addclass("sleepy");a.defaultAwakeTime_=void 0===b?1E3:b;a.wake=function(b){this.remclass("asleep").addclass("awake");window.clearTimeout(this.timeoutId_);this.timeoutId_=window.setTimeout(function(){a.sleep()},void 0===b?a.defaultAwakeTime_:b)};a.sleep=function(){window.clearTimeout(this.timeoutId_);this.timeoutId_=void 0;this.remclass("awake").addclass("asleep")};a.sleep();return a};noh.IBlind=function(){};noh.IBlind.prototype.down=function(){};
noh.IBlind.prototype.roll=function(a){};noh.Blind=function(a){var b=noh.div(arguments).addclass("noh blind content");noh.Element.call(this,"div",b);this.addclass("noh blind");this.content_=b;this.roll(!1);var c=this;this.$.show(function(){c.roll(c.down())})};noh.Blind.prototype=new noh.Element("div");noh.Blind.prototype.down=function(){return this.down_};
noh.Blind.prototype.roll=function(a){var b=this.$,c=this.content_.$,d=c.width(),e=c.height();c.css("clip","rect(0px "+d+"px "+(a?e:0)+"px 0px");a?(this.content_.remclass("hidden"),this.content_.addclass("visible")):(this.content_.remclass("visible"),this.content_.addclass("hidden"));b.width(d);b.height(a?e:0);this.down_=a;return this};noh.blind=function(a){return new noh.Blind(arguments)};noh.IOneOf=function(){};noh.IOneOf.prototype.selected=function(){};noh.IOneOf.prototype.select=function(a){};
noh.OneOf=function(a){for(var b=noh.organize(arguments),c=0;c<b.nodes.length;++c){var d=noh.blind(b.nodes[c]);b.nodes[c]=d;d.oneOfIdx_=c}noh.Element.call(this,"div",b.attrs,b.nodes);this.addclass("noh oneof");this.selected_=-1};noh.OneOf.prototype=new noh.Element("div");noh.OneOf.prototype.selected=function(){return this.selected_};
noh.OneOf.prototype.select=function(a){a instanceof noh.Node?a=a.oneOfIdx_:null===a&&(a=-1);var b=this.length;if(-1>a||a>=b)a=-1;-1!=this.selected_&&this[this.selected_].roll(!1);-1!=a&&this[a].roll(!0);this.selected_=a;return this};noh.OneOf.prototype.selectModulo_=function(a){return this.select(0>a?this.length-1:a%this.length)};noh.OneOf.prototype.next=function(){return this.selectModulo_(this.selected()+1)};noh.OneOf.prototype.prev=function(){return this.selectModulo_(this.selected()-1)};
noh.oneof=function(a){return new noh.OneOf(arguments)};noh.details=function(a){var b=noh.div(arguments).addclass("noh details content"),c=noh.blind(b),b=noh.button("details...").addclass("noh details button").attr("title","show/hide details");b.on("click",function(){c.roll(!c.down())});return noh.div(noh.div(b),noh.div(c)).addclass("noh details")};
noh.Reel=function(a,b,c,d){for(var e=noh.organize(arguments,3),f=0;f<e.nodes.length;++f){var h=noh.div(e.nodes[f]).addclass("noh reel element");e.nodes[f]=h}noh.Element.call(this,"div",e.attrs,e.nodes);this.addclass("noh reel");this.lines=a;this.rotation=0;this.width=b;this.height=c;this.chksize();var g=this;this.$.show(function(){g.update()});this.selected_=-1};noh.Reel.prototype=new noh.Element("div");noh.Reel.prototype.selected=function(){return this.selected_};
noh.Reel.prototype.select=function(a){if(-1>a||a>=this.length)a=-1;if(this.selected_==a)return this;-1!=this.selected_&&this.getelem(this.selected_).remclass("selected");-1!=a&&this.getelem(a).addclass("selected");this.selected_=a;return this};
noh.Reel.prototype.chksize=function(){var a=0;if("automatic"==this.width)for(var b=0;b<this.length;++b)esize=this[b].$.width(),esize>a&&(a=esize);else if("dynamic"==this.width)for(b=0;b<this.lines;++b)esize=this.getelem(b).$.width(),esize>a&&(a=esize);else a=this.width;this.css("min-width",a).css("max-width",a).css("width",a);this.exactwidth_=a;a=0;if("automatic"==this.height){for(b=0;b<this.length;++b)esize=this[b].$.height(),esize>a&&(a=esize);a*=this.lines}else if("dynamic"==this.height){for(b=
0;b<this.lines;++b)esize=this.getelem(b).$.height(),esize>a&&(a=esize);a*=this.lines}else a=this.height;this.css("min-height",a).css("max-height",a).css("height",a);this.exactheight_=a};noh.Reel.prototype.fixLineNr_=function(a){for(;0>a;)a+=this.length;for(;a>=this.length;)a-=this.length;return a};noh.Reel.prototype.getelem=function(a){return this[this.fixLineNr_(a-this.rotation)]};
noh.Reel.prototype.update=function(a){void 0!==a&&(this.lines=a);this.chksize();for(a=0;a<this.length;++a){var b=this.getelem(a);b.remclass("selected");a<this.lines?(b.remclass("hidden").addclass("visible"),b.css("top",""+a*this.exactheight_/this.lines+"px")):(b.remclass("visible").addclass("hidden"),b.css("top",""+(this.length-a-1)*this.exactheight_/(this.length-this.lines)+"px"))}-1!=this.selected_&&this.getelem(this.selected_).addclass("selected");return this};
noh.Reel.prototype.rotate=function(a){this.rotation=this.fixLineNr_(this.rotation+a);return this.update()};noh.Reel.prototype.spin=function(a,b,c){if(this.intervalId_)console.error("The reel is already spinning!");else{b&&(a+=Math.round(Math.random()*b));var d=this;this.intervalId_=window.setInterval(function(){0==a?(window.clearInterval(d.intervalId_),d.intervalId_=void 0):0<a?(d.rotate(1),--a):(d.rotate(-1),++a)},c?c:200)}};
noh.reel=function(a,b,c,d){var e=noh.organize(arguments,3);return new noh.Reel(a,b,c,e.attrs,e.nodes)};noh.fancy=function(a,b){a.addclass("fancy");if(-1!=noh.arr.indexOf(a.tag,["h1","h2","h3","h4"]))a.on("click",function(){this.noh.scroll()});return a};noh.ukbd=function(a){var b=/(https?|ftp):\/\//;a=a.split(/\s+/).map(function(a){return b.test(a)?noh.a({href:a,target:"_blank"},a):" "+a+" "});return noh.kbd(a)};noh.log={};
noh.log.data2str=function(a){var b="";0<a.length&&(b+=a[0]);for(var c=1;c<a.length;++c)b=b+" "+a[c].toString();return b};noh.log.ILogger=function(){};noh.log.ILogger.prototype.log=function(a,b){};noh.log.Little=function(){noh.Element.call(this,"div");this.addclass("noh log little")};noh.log.Little.prototype=new noh.Element("div");noh.log.Little.prototype.log=function(a,b){this.length&&this.rem();var c=noh.ukbd(noh.log.data2str(b)).addclass("noh log element").addclass(a);this.add(c)};
noh.log.little=function(){return new noh.log.Little};noh.log.slittle=function(a){var b=noh.log.little();a=noh.sleepy(b,a);a.log_=a.log;a.log=function(a,b){this.log_(a,b);this.wake()};return a};noh.log.IConsole=function(){};noh.log.IConsole.prototype.log=function(a){};noh.log.IConsole.prototype.info=function(a){};noh.log.IConsole.prototype.warn=function(a){};noh.log.IConsole.prototype.error=function(a){};noh.log.L2C=function(a){this.logger=a};
noh.log.L2C.prototype.log=function(a){this.logger.log("info",arguments)};noh.log.L2C.prototype.info=function(a){this.logger.log("info",arguments)};noh.log.L2C.prototype.warn=function(a){this.logger.log("warning",arguments)};noh.log.L2C.prototype.error=function(a){this.logger.log("error",arguments)};noh.log.L2C.prototype.debug=function(a){this.logger.log("debug",arguments)};noh.log.L2C.prototype.install=function(){window.console=this};noh.log.l2c=function(a){return new noh.log.L2C(a)};
noh.log.C2L=function(a){this.console=a};noh.log.C2L.prototype.log=function(a,b){/error/.test(a)?this.console.error.apply(this.console,b):/warning/.test(a)?this.console.warn.apply(this.console,b):/debug/.test(a)&&this.console.debug instanceof Function?this.console.debug.apply(this.console,b):this.console.info.apply(this.console,b)};noh.log.c2l=function(a){return new noh.log.C2L(a)};noh.log.Multi=function(a){this.loggers=a};
noh.log.Multi.prototype.log=function(a,b){for(var c=0;c<this.loggers.length;++c)this.loggers[c].log(a,b)};noh.log.multi=function(a){return new noh.log.Multi(a)};noh.log.Filter=function(a,b){this.logger=a;this.filter=b};noh.log.Filter.prototype.log=function(a,b){this.logger.log(a,this.filter(b))};noh.log.filter=function(a,b){return new noh.log.Filter(a,b)};
noh.log.addtime=function(a){return noh.log.filter(a,function(a){var c=new Date;return["["+noh.str.prefix(""+c.getHours(),"0",2)+":"+noh.str.prefix(""+c.getMinutes(),"0",2)+":"+noh.str.prefix(""+c.getSeconds(),"0",2)+"]"].concat(Array.prototype.slice.call(a,0))})};noh.log.limitlen=function(a,b){return noh.log.filter(a,function(a){a=noh.log.data2str(a);return[noh.str.limitlen(a,b)]})};
noh.log.reel=function(a,b){for(var c=2*a+1,d=void 0===b?1E4:b,e=[],f=0;f<c;++f)e.push(noh.log.slittle(d));c=noh.reel(a,"automatic","automatic",e);c.select(a-1);logger=noh.div(c).addclass("noh log reel");logger.reel=c;logger.log=function(a,b){this.reel.getelem(this.reel.lines)[0].log(a,b);this.reel.rotate(-1)};logger.setlines=function(a){var b=a-this.reel.lines;this.reel.lines=a;this.reel.rotate(b)};return logger};
noh.cmdline=function(a){var b=noh.input().attr("type","text").attr("size",a).attr("placeholder",'alert("hello world")').addclass("noh cmdline");a=noh.button(String.fromCharCode(8629)).attr("title","Press enter to run the command.").addclass("noh cmdline");var c=noh.div(b,a).css("display","inline-block").addclass("noh cmdline");c.run=function(){var a=b.$.val();console.log(a);try{var c=eval(a);void 0!==c&&console.log(c)}catch(f){console.error(f)}b.$.val("")};b.on("keypress",function(a){13==a.which&&
c.run()});a.on("click",function(){c.run()});return c};noh.ISelectable=function(){};noh.ISelectable.prototype.selected=function(){};noh.ISelectable.prototype.toggle=function(){};noh.MenuItem=function(a){noh.Element.call(this,"div",{"class":"noh menu item"},a);this.on("click",function(){this.noh.toggle();return!1})};noh.MenuItem.prototype=new noh.Element("div");noh.MenuItem.prototype.toggle=function(){this.toggleclass("selected")};noh.MenuItem.prototype.selected=function(){return this.hasclass("selected")};
noh.menuitem=function(a){return new noh.MenuItem(a)};noh.bigmenuitem=function(a,b){var c=noh.oneof(b),d=noh.div(noh.div(a),noh.div(c));a.toggle_orig_=a.toggle;a.toggle=function(){d.toggle()};d.toggle=function(){a.toggle_orig_();c.select(this.selected()?0:-1)};d.selected=function(){return a.selected()};return d};
noh.Menu=function(a){var b=noh.organize(arguments);noh.Element.call(this,"div",b.attrs,b.nodes);this.items_=b.nodes;for(b=0;b<this.items_.length;++b){var c=this.items[b];c.selected()&&c.toggle();c.menu_=this;c.menuIdx_=b;c.toggle_orig_=c.toggle;c.toggle=function(){this.menu_.select(this.selected()?-1:this.menuIdx_)}}this.selected_=-1};noh.Menu.prototype=new noh.Element("div");noh.Menu.prototype.selected=function(){return this.selected_};
noh.Menu.prototype.select=function(a){-1!=this.selected_&&this.items_[selected_].toggle_orig_();this.selected_=a;-1!=a&&this.items_[a].toggle_orig_()};noh.menu=function(a){return new noh.Menu(arguments)};noh.submenu=function(a,b){var c=bigmenuitem(a,b);c.menu=b;return c};function noh_tests_init(){var a=$("#noh_tests");0!=a.length&&(noh_tests().attachToDOM(a[0]),SyntaxHighlighter.all())}$(document).ready(noh_tests_init);function tdiv(a){return noh.div({"class":"noh stest"},arguments)}function runstest(a){var b=a();return tdiv(noh.ul(noh.li(noh.h4("Source code:"),tdiv(noh.srccode(a))),noh.li(noh.h4("Result:"),tdiv(b)),noh.li(noh.h4("Result source code (html):"),tdiv(noh.syntaxhl("html",b.dom.outerHTML||(new XMLSerializer).serializeToString(b.dom))))))}
function runstests(a){var b=[],c;for(c in a)b.push(noh.dt(noh.fancy(noh.h3("stest: ",c))).css("padding","20px"),noh.dd(runstest(a[c])));return noh.dl(b)}function noh_tests(){return noh.div(noh.fancy(noh.h2("Simple tests")),runstests(tests))}
var tests={simple:function(){return noh.ex.simple()},goofy:function(){return noh.ex.goofy()},silly:function(){return noh.ex.silly()},whitey:function(){return noh.ex.whitey()},shiny:function(){return noh.ex.shiny()},shiny:function(){return noh.ex.shiny()},idiots:function(){return noh.ex.idiots()},colors:function(){return noh.div(noh.sdiv(noh.ex.color("red")),noh.sdiv(noh.ex.color("green")),noh.sdiv(noh.ex.color("blue")))},rainbows:function(){return noh.div(noh.sdiv(noh.ex.rainbow(5)),noh.sdiv(noh.ex.rainbow(10)),
noh.sdiv(noh.ex.rainbow(15)))},h16:function(){return noh.div(noh.h1("Some h1 text"),noh.h2("Some h2 text"),noh.h3("Some h3 text"),noh.h4("Some h4 text"),noh.h5("Some h5 text"),noh.h6("Some h6 text"))},fancyh16:function(){return noh.div(noh.fancy(noh.h1("Some h1 text")),noh.fancy(noh.h2("Some h2 text")),noh.fancy(noh.h3("Some h3 text")),noh.fancy(noh.h4("Some h4 text")),noh.fancy(noh.h5("Some h5 text")),noh.fancy(noh.h6("Some h6 text")))},srccode:function(){return noh.srccode(tests.srccode)},overlay:function(){var a=
noh.div({style:"margin: 10px; color: green; font-size: xx-large"}," overlay BLEBLE",noh.br(),"BLUBLU").addclass("pretty"),b=noh.div({style:"margin: 10px; color: blue; font-size: x-large"}," overlay BLEBLE",noh.br(),"BLUBLU").addclass("pretty"),c=noh.div({style:"margin: 30px; color: red; font-size: large"}," overlay",noh.br(),"BLU").addclass("pretty"),d=noh.overlay(a,b,c).addclass("left top");d.$.click(function(){d.hide()});var e={"class":"noh link",style:"padding: 5px"},a=noh.a(e,"overlay.show()"),
b=noh.a(e,"overlay.hide()"),c=noh.a(e,"overlay.show(1)"),f=noh.a(e,"overlay.hide(1)"),h=noh.a(e,"overlay.show(2)"),g=noh.a(e,"overlay.hide(2)"),k=noh.a(e,'overlay.parent.addclass("smooth")'),l=noh.a(e,'overlay.parent.remclass("smooth")'),m=noh.a(e,'overlay[1].addclass("pretty")'),n=noh.a(e,'overlay[1].remclass("pretty")'),p=noh.a(e,'overlay.remclass("top").addclass("bottom")'),e=noh.a(e,'overlay.remclass("bottom").addclass("top")');a.$.click(function(){d.show()});b.$.click(function(){d.hide()});c.$.click(function(){d.show(1)});
f.$.click(function(){d.hide(1)});h.$.click(function(){d.show(2)});g.$.click(function(){d.hide(2)});k.$.click(function(){d.parent.addclass("smooth")});l.$.click(function(){d.parent.remclass("smooth")});m.$.click(function(){d[1].addclass("pretty")});n.$.click(function(){d[1].remclass("pretty")});p.$.click(function(){d.remclass("top").addclass("bottom")});e.$.click(function(){d.remclass("bottom").addclass("top")});return noh.div(a,b,noh.br(),c,f,noh.br(),h,g,noh.br(),k,l,noh.br(),m,n,noh.br(),p,e,noh.table1r({style:"border: 6px ridge green"},
noh.td(d)))},overlay2:function(){var a=noh.div({style:"margin: 10px; color: green; font-size: xx-large"}," overlay BLEBLE",noh.br(),"BLUBLU").addclass("pretty"),b=noh.div({style:"margin: 10px; color: blue; font-size: x-large"}," overlay BLEBLE",noh.br(),"BLUBLU").addclass("pretty"),c=noh.div({style:"margin: 30px; color: red; font-size: large"}," overlay",noh.br(),"BLU").addclass("pretty"),d=noh.overlay(a,b,noh.ex.silly().addclass("pretty"),c).addclass("top");d.css("right","10px");d.$.click(function(){d.hide()});
var e={"class":"noh link",style:"padding: 5px"},a=noh.a(e,"overlay.show()"),b=noh.a(e,"overlay.hide()"),c=noh.a(e,"overlay.show(1)"),f=noh.a(e,"overlay.hide(1)"),h=noh.a(e,"overlay.show(2)"),g=noh.a(e,"overlay.hide(2)"),k=noh.a(e,'overlay.parent.addclass("smooth")'),l=noh.a(e,'overlay.parent.remclass("smooth")'),m=noh.a(e,'overlay.remclass("top").addclass("bottom")'),n=noh.a(e,'overlay.remclass("bottom").addclass("top")'),p=noh.a(e,'overlay.css("right", "30px")'),q=noh.a(e,'overlay.css("right", "130px")'),
e=noh.a(e,'overlay.css("right", "230px")');a.$.click(function(){d.show()});b.$.click(function(){d.hide()});c.$.click(function(){d.show(1)});f.$.click(function(){d.hide(1)});h.$.click(function(){d.show(2)});g.$.click(function(){d.hide(2)});k.$.click(function(){d.parent.addclass("smooth")});l.$.click(function(){d.parent.remclass("smooth")});m.$.click(function(){d.remclass("top").addclass("bottom")});n.$.click(function(){d.remclass("bottom").addclass("top")});p.$.click(function(){d.css("right","30px")});
q.$.click(function(){d.css("right","130px")});e.$.click(function(){d.css("right","230px")});return noh.div(a,b,noh.br(),c,f,noh.br(),h,g,noh.br(),k,l,noh.br(),m,n,noh.br(),p,q,e,noh.table1r({style:"border: 6px ridge green"},noh.td(d)))},overlay3:function(){var a=noh.log.reel(15).addclass("pretty");install_logger(a);var b=noh.cmdline(40).addclass("pretty"),c=noh.overlay(a,b);c.addclass("bottom");c.addclass("smooth");c.css("right","10px");var d={"class":"noh link",style:"padding: 5px"},a=noh.a(d,"overlay.show()"),
b=noh.a(d,"overlay.hide()"),e=noh.a(d,"overlay.show(1)"),f=noh.a(d,"overlay.hide(1)"),h=noh.a(d,"overlay.show(2)"),g=noh.a(d,"overlay.hide(2)"),k=noh.a(d,'overlay.parent.addclass("smooth")'),l=noh.a(d,'overlay.parent.remclass("smooth")'),m=noh.a(d,'overlay.remclass("top").addclass("bottom")'),n=noh.a(d,'overlay.remclass("bottom").addclass("top")'),p=noh.a(d,'overlay.css("right", "30px")'),q=noh.a(d,'overlay.css("right", "130px")'),d=noh.a(d,'overlay.css("right", "230px")');a.$.click(function(){c.show()});
b.$.click(function(){c.hide()});e.$.click(function(){c.show(1)});f.$.click(function(){c.hide(1)});h.$.click(function(){c.show(2)});g.$.click(function(){c.hide(2)});k.$.click(function(){c.parent.addclass("smooth")});l.$.click(function(){c.parent.remclass("smooth")});m.$.click(function(){c.remclass("top").addclass("bottom")});n.$.click(function(){c.remclass("bottom").addclass("top")});p.$.click(function(){c.css("right","30px")});q.$.click(function(){c.css("right","130px")});d.$.click(function(){c.css("right",
"230px")});return noh.div(a,b,noh.br(),e,f,noh.br(),h,g,noh.br(),k,l,noh.br(),m,n,noh.br(),p,q,d,noh.table1r({style:"border: 6px ridge green"},noh.td(c)))},sleepy:function(){var a=noh.div({style:"color: green; font-size: xx-large"}," sleepy BLEBLE",noh.br(),"BLUBLU"),b=noh.sleepy(a,2E3),c={"class":"noh link",style:"padding: 5px"},a=noh.a(c,"sleepy.wake()"),d=noh.a(c,"sleepy.sleep()"),e=noh.a(c,'sleepy.parent.addclass("smooth")'),c=noh.a(c,'sleepy.parent.remclass("smooth")');a.$.click(function(){b.wake()});
d.$.click(function(){b.sleep()});e.$.click(function(){b.parent.addclass("smooth")});c.$.click(function(){b.parent.remclass("smooth")});return noh.div(a,d,e,c,noh.table1r({style:"border: 6px ridge green"},noh.td(b)))},blind:function(){var a=noh.blind(noh.div({style:"color: blue; font-size: xx-large"},"blind BLEBLE",noh.br(),"BLUBLU")),b={"class":"noh link",style:"padding: 5px"},c=noh.a(b,"blind.roll(true)"),d=noh.a(b,"blind.roll(false)"),b=noh.a(b,"alert(blind.down())");c.$.click(function(){a.roll(!0)});
d.$.click(function(){a.roll(!1)});b.$.click(function(){alert(a.down())});return noh.div(c,d,b,noh.table1r({style:"border: 6px ridge green"},noh.td(a)))},oneof:function(){var a=noh.oneof(noh.div({style:"font-style: italic; color: green; font-size: xx-large"},"BLABLA"),noh.div({style:"color: blue; font-size: xx-large"},"BLEBLE",noh.br(),"BLUBLU"),noh.div({style:"color: red; font-size: xx-large"},"BLIBLI",noh.br(),noh.br(),"BLZBLZ"));a.select(0);var b={"class":"noh link",style:"padding: 5px"},c=noh.a(b,
"oneof.next()"),d=noh.a(b,"oneof.prev()"),e=noh.a(b,"oneof.select(1)"),b=noh.a(b,"oneof.select(-1)");c.$.click(function(){a.next()});d.$.click(function(){a.prev()});e.$.click(function(){a.select(1)});b.$.click(function(){a.select(-1)});return noh.div(c,d,e,b,noh.table1r({style:"border: 6px ridge green"},noh.td(a)))},details:function(){var a={style:"color: brown; font-size: x-large; width: 400px;"};return noh.div(noh.span(a,"BASIC INFO"),noh.details(noh.div(noh.div(a,"bjkalb DETAILS"),noh.div(a,"fjdsklfsd   DETAILS"),
noh.div("fjdsklf jksfl dsjlf djksdfl DETAILS"))))}};
function gen_test_reel(a){var b={"class":"noh link",style:"padding: 5px"},c=noh.a(b,'reel.parent.addclass("smooth")'),d=noh.a(b,'reel.parent.remclass("smooth")'),e=noh.a(b,'reel.parent.addclass("fast")'),f=noh.a(b,'reel.parent.remclass("fast")'),h=noh.a(b,'reel.parent.addclass("slow")'),g=noh.a(b,'reel.parent.remclass("slow")'),k=noh.a(b,'reel.parent.addclass("very_slow")'),l=noh.a(b,'reel.parent.remclass("very_slow")'),m=noh.a(b,'reel.addclass("fancy")'),n=noh.a(b,'reel.remclass("fancy")'),p=noh.a(b,
"reel.rotate(1)"),q=noh.a(b,"reel.rotate(2)"),r=noh.a(b,"reel.rotate(3)"),s=noh.a(b,"reel.rotate(-1)"),t=noh.a(b,"reel.rotate(-2)"),u=noh.a(b,"reel.rotate(-3)"),v=noh.a(b,"reel.spin(20)"),w=noh.a(b,"reel.spin(-12, -4, 100)"),x=noh.a(b,"reel.update(1)"),y=noh.a(b,"reel.update(2)"),z=noh.a(b,"reel.update(3)"),A=noh.a(b,"reel.update(5)"),b=noh.a(b,"reel.update(7)");c.$.click(function(){a.parent.addclass("smooth")});d.$.click(function(){a.parent.remclass("smooth")});e.$.click(function(){a.parent.addclass("fast")});
f.$.click(function(){a.parent.remclass("fast")});h.$.click(function(){a.parent.addclass("slow")});g.$.click(function(){a.parent.remclass("slow")});k.$.click(function(){a.parent.addclass("very_slow")});l.$.click(function(){a.parent.remclass("very_slow")});m.$.click(function(){a.addclass("fancy")});n.$.click(function(){a.remclass("fancy")});p.$.click(function(){a.rotate(1)});q.$.click(function(){a.rotate(2)});r.$.click(function(){a.rotate(3)});s.$.click(function(){a.rotate(-1)});t.$.click(function(){a.rotate(-2)});
u.$.click(function(){a.rotate(-3)});v.$.click(function(){a.spin(20)});w.$.click(function(){a.spin(-12,-4,100)});x.$.click(function(){a.update(1)});y.$.click(function(){a.update(2)});z.$.click(function(){a.update(3)});A.$.click(function(){a.update(5)});b.$.click(function(){a.update(7)});return noh.div(c,d,noh.br(),e,f,noh.br(),h,g,noh.br(),k,l,noh.br(),m,n,noh.br(),p,q,r,s,t,u,noh.br(),v,w,noh.br(),x,y,z,A,b,noh.div(noh.table1r(noh.td({style:"border: 6px ridge green"},a))))}
tests.reel1=function(){var a={style:"padding: 5px; border: solid blue; color: black; font-size: large; width: 400px; background: wheat"},a=noh.reel(5,"dynamic","dynamic",noh.div(a,"BLABLA").css("background","green"),noh.div(a,"BLABLA").css("background","blue"),noh.div(a,"BLEBLE",noh.br(),"BLUBLU").css("width","500px"),noh.div(a,"BLEBLE",noh.br(),"BLUBLU").css("width","200px"),noh.div(a,"BLEBLE",noh.br(),"BLUBLU").css("width","220px"),noh.div(a,"BLIBLI",noh.br(),"margin:10px",noh.br(),"BLZBLZ").css("width",
"270px").css("margin","10px"),noh.div(a,"BLIBLI",noh.br(),"margin:20px",noh.br(),"BLZBLZ").css("width","250px").css("margin","20px"),noh.div(a,"BLIBLI",noh.br(),noh.br(),"BLZBLZ").css("width","130px"));a.select(2);return gen_test_reel(a)};
function reelnr(a,b){for(var c=function(a,b){for(var c=""+a;c.length<b;)c="0"+c;return c},d=[],e={style:"font-family: monospace; margin: 5px; padding: 15px; border: solid black; color: black; font-size: large; width: 100; background: wheat"},f=a;f<=b;++f)d.push(noh.div(e,""+c(f,3)));return noh.reel(3,"automatic","automatic",d).select(1).addclass("smooth").addclass("fancy")}tests.reel2=function(){var a=reelnr(1,12);return gen_test_reel(a)};tests.kbd=function(){return noh.div(noh.ukbd("fjdkl http://www.google.pl google fjsdk ftp://blabal fjdsl http://mareklangiewicz.pl fds fjdsklfds"))};
function get_test_logger(a){var b={"class":"noh link",style:"padding: 5px"},c=noh.a(b,'logger.log("info", ["dupa info"])'),d=noh.a(b,'logger.log("warning", ["dupa warning"])'),e=noh.a(b,'logger.log("error", ["dupa error", "dupa error2", 3, 4, window])'),f=noh.a(b,'logger.log("info warning", ["dupa info warning"])'),h=noh.a(b,"noh.log.l2c(logger).install()"),g=noh.a(b,"noh.log.l2c(noh.log.addtime(logger)).install()"),k=noh.a(b,'logger.parent.addclass("smooth")'),l=noh.a(b,'logger.parent.remclass("smooth")'),
m=noh.a(b,'logger.addclass("pretty")'),n=noh.a(b,'logger.remclass("pretty")'),p=noh.a(b,"logger.setlines(5)"),b=noh.a(b,"logger.setlines(9)");c.$.click(function(){a.log("info",["dupa info"])});d.$.click(function(){a.log("warning",["dupa warning"])});e.$.click(function(){a.log("error",["dupa error","dupa error2",3,4,window])});f.$.click(function(){a.log("info warning",["dupa info warning"])});h.$.click(function(){noh.log.l2c(a).install()});g.$.click(function(){noh.log.l2c(noh.log.limitlen(noh.log.addtime(a),
20)).install()});k.$.click(function(){a.parent.addclass("smooth")});l.$.click(function(){a.parent.remclass("smooth")});m.$.click(function(){a.addclass("pretty")});n.$.click(function(){a.remclass("pretty")});p.$.click(function(){a.setlines(5)});b.$.click(function(){a.setlines(9)});return noh.div(c,noh.br(),d,noh.br(),e,noh.br(),f,noh.br(),k,l,noh.br(),m,n,noh.br(),h,noh.br(),g,noh.br(),p,b,noh.br(),noh.table1r({style:"border: 6px ridge green"},noh.td(a)))}
tests.log_slittle=function(){var a=noh.log.slittle(3E3);return get_test_logger(a)};tests.log_multi=function(){var a=noh.log.slittle(1E3),b=noh.log.slittle(2E3),c=noh.log.slittle(3E3),d=noh.log.c2l(window.console),e=noh.log.multi([a,b,c,d]),a=noh.div(a,b,c);a.log=function(a,b){e.log(a,b)};return get_test_logger(a)};tests.log_reel=function(){var a=noh.log.reel(15);return get_test_logger(a)};
function install_logger(a){noh.log.l2c(noh.log.multi([noh.log.c2l(window.console),noh.log.limitlen(noh.log.addtime(a),40)])).install()}tests.log_install=function(){var a=noh.a({"class":"noh link",style:"padding: 5px"},"install_logger(logger)"),b=noh.log.reel(15,3E4).addclass("pretty smooth");a.$.click(function(){install_logger(b);console.log("Welcome!")});return noh.div(a,noh.table1r({style:"border: 6px ridge green"},noh.td(b)))};tests.cmdline=function(){return noh.cmdline(40)};
