var noh={NotImplementedError:function(a){a&&(this.message=a)}};noh.NotImplementedError.prototype=Error("Not implemented");noh.NotSupportedError=function(a){a&&(this.message=a)};noh.NotSupportedError.prototype=new noh.NotImplementedError("Operation not supported");noh.TAGS="html head body script meta title link div p span a img br hr em i strong table tr th td thead tbody tfoot colgroup col ul ol li dl dt dd h1 h2 h3 h4 h5 h6 form fieldset input textarea label select option b pre code button kbd".split(" ");
noh.body=function(a){return new noh.Element("body",arguments)};noh.link=function(a){return new noh.Element("link",arguments)};noh.div=function(a){return new noh.Element("div",arguments)};noh.p=function(a){return new noh.Element("p",arguments)};noh.span=function(a){return new noh.Element("span",arguments)};noh.a=function(a){return new noh.Element("a",arguments)};noh.img=function(a){return new noh.Element("img",arguments)};noh.br=function(a){return new noh.Element("br",arguments)};
noh.hr=function(a){return new noh.Element("hr",arguments)};noh.em=function(a){return new noh.Element("em",arguments)};noh.i=function(a){return new noh.Element("i",arguments)};noh.strong=function(a){return new noh.Element("strong",arguments)};noh.table=function(a){return new noh.Element("table",arguments)};noh.tr=function(a){return new noh.Element("tr",arguments)};noh.th=function(a){return new noh.Element("th",arguments)};noh.td=function(a){return new noh.Element("td",arguments)};
noh.thead=function(a){return new noh.Element("thead",arguments)};noh.tbody=function(a){return new noh.Element("tbody",arguments)};noh.tfoot=function(a){return new noh.Element("tfoot",arguments)};noh.colgroup=function(a){return new noh.Element("colgroup",arguments)};noh.col=function(a){return new noh.Element("col",arguments)};noh.ul=function(a){return new noh.Element("ul",arguments)};noh.ol=function(a){return new noh.Element("ol",arguments)};noh.li=function(a){return new noh.Element("li",arguments)};
noh.dl=function(a){return new noh.Element("dl",arguments)};noh.dt=function(a){return new noh.Element("dt",arguments)};noh.dd=function(a){return new noh.Element("dd",arguments)};noh.h1=function(a){return new noh.Element("h1",arguments)};noh.h2=function(a){return new noh.Element("h2",arguments)};noh.h3=function(a){return new noh.Element("h3",arguments)};noh.h4=function(a){return new noh.Element("h4",arguments)};noh.h5=function(a){return new noh.Element("h5",arguments)};
noh.h6=function(a){return new noh.Element("h6",arguments)};noh.form=function(a){return new noh.Element("form",arguments)};noh.fieldset=function(a){return new noh.Element("fieldset",arguments)};noh.input=function(a){return new noh.Element("input",arguments)};noh.textarea=function(a){return new noh.Element("textarea",arguments)};noh.label=function(a){return new noh.Element("label",arguments)};noh.select=function(a){return new noh.Element("select",arguments)};
noh.option=function(a){return new noh.Element("option",arguments)};noh.b=function(a){return new noh.Element("b",arguments)};noh.pre=function(a){return new noh.Element("pre",arguments)};noh.code=function(a){return new noh.Element("code",arguments)};noh.button=function(a){return new noh.Element("button",arguments)};noh.kbd=function(a){return new noh.Element("kbd",arguments)};noh.text=function(a){return new noh.Text(a)};
noh.organize=function(a,b,c){b=void 0===b?0:b;c=c?c:{attrs:{},nodes:[]};if(a instanceof noh.Node)c.nodes.push(a);else if("string"===typeof a)c.nodes.push(noh.text(a));else if(noh.arr.isArrayLike(a))for(;b<a.length;++b)noh.organize(a[b],0,c);else if(a instanceof Object)$.extend(c.attrs,a);else if(void 0!==a&&null!==a)throw new TypeError("Unknown argument type: "+typeof a+" value: "+String(a));return c};noh.arr={};noh.arr.push=function(a,b){return b.push.apply(b,a)};
noh.arr.indexOf=function(a,b){for(var c=0;c<b.length;++c)if(a==b[c])return c;return-1};noh.arr.arr2obj=function(a,b){if(null===b)return null;for(var c={},d=0;d<a.length;++d)c[a[d]]=b[d];return c};noh.arr.obj2arr=function(a,b){if(null===b)return null;for(var c=[],d=0;d<a.length;++d)c.push(b[a[d]]);return c};
noh.arr.isArrayLike=function(a){if(void 0==a||null==a)return!1;if(a instanceof jQuery||jQuery.isArray(a))return!0;var b=a.length;if("number"!==typeof b)return!1;if(0==b)return!0;if(0>b)return!1;var c=Object.prototype.hasOwnProperty;return c.call(a,0)&&c.call(a,b-1)?!0:!1};noh.str={};noh.str.limitlen=function(a,b){a.length>b&&(a=a.substr(0,b-3)+"...");return a};noh.str.prefix=function(a,b,c){for(;a.length<c;)a=b+a;return a};noh.Node=function(){this.length=0;this.$=this.dom=this.parent=null};
noh.Node.prototype.add=function(a){a.attachToDOM(this.dom);a.parent=this;Array.prototype.push.call(this,a);return this};noh.Node.prototype.rem=function(){var a=Array.prototype.pop.call(this);a.parent=null;a.detachFromDOM(this.dom);return this};noh.Node.prototype.splice=function(){throw new noh.NotSupportedError;};noh.Node.prototype.attachToDOM=function(a){a.appendChild(this.dom);return this};noh.Node.prototype.detachFromDOM=function(a){a.removeChild(this.dom);return this};
noh.Text=function(a){this.text=a;noh.Node.call(this);this.dom=document.createTextNode(a);this.dom.noh=this;this.$=$(this.dom)};noh.Text.prototype=new noh.Node;noh.Element=function(a,b){this.tag=a;noh.Node.call(this);this.dom=document.createElement(a);this.dom.noh=this;this.$=$(this.dom);var c=noh.organize(arguments,1),d;for(d in c.attrs)this.attr(d,c.attrs[d]);for(d=0;d<c.nodes.length;++d)this.add(c.nodes[d])};noh.Element.prototype=new noh.Node;
noh.Element.prototype.attr=function(a,b){this.$.attr(a,b);return this};noh.Element.prototype.css=function(a,b){this.$.css(a,b);return this};noh.Element.prototype.on=function(a,b){this.$.on(a,b);return this};noh.Element.prototype.addclass=function(a){this.$.addClass(a);return this};noh.Element.prototype.hasclass=function(a){return this.$.hasClass(a)};noh.Element.prototype.toggleclass=function(a){this.$.toggleClass(a);return this};noh.Element.prototype.remclass=function(a){this.$.removeClass(a);return this};
noh.scroll=function(a,b){$("html,body").animate({scrollTop:a},b?b:1E3)};noh.Element.prototype.scroll=function(a){noh.scroll(this.$.offset().top,a);return this};noh.table1r=function(a){var b=noh.organize(arguments);return noh.table(b.attrs,noh.tbody(noh.tr(b.nodes)))};noh.tablebar=function(a){for(var b=noh.organize(arguments),c=[],d=0;d<b.children.length;++d)c.push(noh.td(b.nodes[d]));return noh.table1r({"class":"noh bar"},b.attrs,c)};
noh.sdiv=function(a){return noh.div({style:"margin:10px; padding:10px; border:solid 2px"},arguments)};noh.ex={};noh.ex.simple=function(){return noh.span("Simpleeeee! kind of man!").css("padding",10).css("background-color","lightgray").css("border","solid 2px")};noh.ex.goofy=function(){return noh.span("Daaaaa..").css("padding",20).css("background-color","gray").css("border","solid 4px")};
noh.ex.silly=function(){return noh.span({style:"padding: 25px; font-size:xx-large; color:red; background-color:yellow; border:solid 1px red; border-radius:40px"},":-)")};noh.ex.whitey=function(){return noh.span({style:"padding:15px; color:white; background-color:white; border:solid 2px white"},"White on white")};noh.ex.shiny=function(){return noh.span({style:"padding:10px; color:red; background-color:pink; border:solid 2px red"},":*")};
noh.ex.idiots=function(){return noh.div(noh.ex.simple(),noh.ex.goofy(),noh.ex.silly())};noh.ex.color=function(a){return noh.span({style:"padding:8px"},"C").css("color",a).css("background-color",a)};noh.ex.rainbow=function(a){for(var b=[],c=0;c<a;++c)b.push(noh.ex.color("hsl("+360*c/a+",100%,50%)"));return noh.span(b)};noh.syntaxhl=function(a,b){return noh.pre({"class":"brush: "+a+"; toolbar: false"},b)};noh.srccode=function(a){return noh.syntaxhl("js",a.toString())};
noh.overlay=function(a){var b=noh.div(arguments).addclass("noh overlay");b.show=function(a){a=void 0===a?this:this[a];if(!a.hasclass("hidden"))return b;(this.hasclass("left")||this.hasclass("right"))&&a.css("left","").css("right","");(this.hasclass("top")||this.hasclass("bottom"))&&a.css("top","").css("bottom","");a.remclass("hidden").addclass("visible");return this};b.hide=function(a){a=void 0===a?this:this[a];if(a.hasclass("hidden"))return b;var d=$(window).width(),e=$(window).height(),f=a.$.outerWidth(!0),
g=a.$.outerHeight(!0),h=a.$.offset(),k=h.left,h=h.top-$(document).scrollTop(),d=d-k-f,e=e-h-g;this.hasclass("left")?a.css("left",""+(-k-f-5)+"px"):this.hasclass("right")?a===this?a.css("right",""+(-d-f-5)+"px"):a.css("left",""+(f+d+5)+"px"):this.hasclass("top")?a.css("top",""+(-h-g-5)+"px"):this.hasclass("bottom")&&(a===this?a.css("bottom",""+(-e-g-5)+"px"):a.css("top",""+(g+e+5)+"px"));a.remclass("visible").addclass("hidden");return this};return b};
noh.sleepy=function(a,b){a.addclass("noh").addclass("sleepy");a.defaultAwakeTime_=void 0===b?1E3:b;a.wake=function(b){this.remclass("asleep").addclass("awake");window.clearTimeout(this.timeoutId_);this.timeoutId_=window.setTimeout(function(){a.sleep()},void 0===b?a.defaultAwakeTime_:b)};a.sleep=function(){window.clearTimeout(this.timeoutId_);this.timeoutId_=void 0;this.remclass("awake").addclass("asleep")};a.sleep();return a};noh.IBlind=function(){};noh.IBlind.prototype.down=function(){};
noh.IBlind.prototype.roll=function(a){};noh.Blind=function(a){var b=noh.div(arguments).addclass("noh blind content");noh.Element.call(this,"div",b);this.addclass("noh blind");this.content_=b;this.roll(!1);var c=this;this.$.show(function(){c.roll(c.down())})};noh.Blind.prototype=new noh.Element("div");noh.Blind.prototype.down=function(){return this.down_};
noh.Blind.prototype.roll=function(a){var b=this.$,c=this.content_.$,d=c.width(),e=c.height();c.css("clip","rect(0px "+d+"px "+(a?e:0)+"px 0px");a?(this.content_.remclass("hidden"),this.content_.addclass("visible")):(this.content_.remclass("visible"),this.content_.addclass("hidden"));b.width(d);b.height(a?e:0);this.down_=a;return this};noh.blind=function(a){return new noh.Blind(arguments)};noh.IOneOf=function(){};noh.IOneOf.prototype.selected=function(){};noh.IOneOf.prototype.select=function(a){};
noh.OneOf=function(a){for(var b=noh.organize(arguments),c=0;c<b.nodes.length;++c){var d=noh.blind(b.nodes[c]);b.nodes[c]=d;d.oneOfIdx_=c}noh.Element.call(this,"div",b.attrs,b.nodes);this.addclass("noh oneof");this.selected_=-1};noh.OneOf.prototype=new noh.Element("div");noh.OneOf.prototype.selected=function(){return this.selected_};
noh.OneOf.prototype.select=function(a){a instanceof noh.Node?a=a.oneOfIdx_:null===a&&(a=-1);var b=this.length;if(-1>a||a>=b)a=-1;-1!=this.selected_&&this[this.selected_].roll(!1);-1!=a&&this[a].roll(!0);this.selected_=a;return this};noh.OneOf.prototype.selectModulo_=function(a){return this.select(0>a?this.length-1:a%this.length)};noh.OneOf.prototype.next=function(){return this.selectModulo_(this.selected()+1)};noh.OneOf.prototype.prev=function(){return this.selectModulo_(this.selected()-1)};
noh.oneof=function(a){return new noh.OneOf(arguments)};noh.details=function(a){var b=noh.div(arguments).addclass("noh details content"),c=noh.blind(b),b=noh.button("details...").addclass("noh details button").attr("title","show/hide details");b.on("click",function(){c.roll(!c.down())});b=noh.div(noh.div(b),noh.div(c)).addclass("noh details");b.down=function(){return c.down()};b.roll=function(a){return c.roll(a)};return b};
noh.Reel=function(a,b,c,d){for(var e=noh.organize(arguments,3),f=0;f<e.nodes.length;++f){var g=noh.div(e.nodes[f]).addclass("noh reel element");e.nodes[f]=g}noh.Element.call(this,"div",e.attrs,e.nodes);this.addclass("noh reel");this.lines=a;this.rotation=0;this.width=b;this.height=c;this.chksize();var h=this;this.$.show(function(){h.update()});this.selected_=-1};noh.Reel.prototype=new noh.Element("div");noh.Reel.prototype.selected=function(){return this.selected_};
noh.Reel.prototype.select=function(a){if(-1>a||a>=this.length)a=-1;if(this.selected_==a)return this;-1!=this.selected_&&this.getelem(this.selected_).remclass("selected");-1!=a&&this.getelem(a).addclass("selected");this.selected_=a;return this};
noh.Reel.prototype.chksize=function(){var a=0,b=0;if("automatic"==this.width)for(var c=0;c<this.length;++c)b=this[c].$.width(),b>a&&(a=b);else if("dynamic"==this.width)for(c=0;c<this.lines;++c)b=this.getelem(c).$.width(),b>a&&(a=b);else a=this.width;this.css("min-width",a).css("max-width",a).css("width",a);this.exactwidth_=a;a=0;if("automatic"==this.height){for(c=0;c<this.length;++c)b=this[c].$.height(),b>a&&(a=b);a*=this.lines}else if("dynamic"==this.height){for(c=0;c<this.lines;++c)b=this.getelem(c).$.height(),
b>a&&(a=b);a*=this.lines}else a=this.height;this.css("min-height",a).css("max-height",a).css("height",a);this.exactheight_=a};noh.Reel.prototype.fixLineNr_=function(a){for(;0>a;)a+=this.length;for(;a>=this.length;)a-=this.length;return a};noh.Reel.prototype.getelem=function(a){return this[this.fixLineNr_(a-this.rotation)]};
noh.Reel.prototype.update=function(a){void 0!==a&&(this.lines=a);this.chksize();for(a=0;a<this.length;++a){var b=this.getelem(a);b.remclass("selected");a<this.lines?(b.remclass("hidden").addclass("visible"),b.css("top",""+a*this.exactheight_/this.lines+"px")):(b.remclass("visible").addclass("hidden"),b.css("top",""+(this.length-a-1)*this.exactheight_/(this.length-this.lines)+"px"))}-1!=this.selected_&&this.getelem(this.selected_).addclass("selected");return this};
noh.Reel.prototype.rotate=function(a){this.rotation=this.fixLineNr_(this.rotation+a);return this.update()};noh.Reel.prototype.spin=function(a,b,c){if(this.intervalId_)console.error("The reel is already spinning!");else{b&&(a+=Math.round(Math.random()*b));var d=this;this.intervalId_=window.setInterval(function(){0==a?(window.clearInterval(d.intervalId_),d.intervalId_=void 0):0<a?(d.rotate(1),--a):(d.rotate(-1),++a)},c?c:200)}};
noh.reel=function(a,b,c,d){var e=noh.organize(arguments,3);return new noh.Reel(a,b,c,e.attrs,e.nodes)};noh.fancy=function(a,b){a.addclass("fancy");if(-1!=noh.arr.indexOf(a.tag,["h1","h2","h3","h4"]))a.on("click",function(){this.noh.scroll()});else if("a"==a.tag){var c=a.$.attr("href");if(c&&0<c.length&&"#"==c[0])a.on("click",function(){noh.scroll($($(this).attr("href")).offset().top)})}return a};
noh.ukbd=function(a){var b=/(https?|ftp):\/\//;a=a.split(/\s+/).map(function(a){return b.test(a)?noh.a({href:a,target:"_blank"},a):" "+a+" "});return noh.kbd(a)};noh.log={};noh.log.data2str=function(a){var b="";0<a.length&&(b+=a[0]);for(var c=1;c<a.length;++c)b=b+" "+a[c].toString();return b};noh.log.ILogger=function(){};noh.log.ILogger.prototype.log=function(a,b){};noh.log.Little=function(){noh.Element.call(this,"div");this.addclass("noh log little")};noh.log.Little.prototype=new noh.Element("div");
noh.log.Little.prototype.log=function(a,b){this.length&&this.rem();var c=noh.ukbd(noh.log.data2str(b)).addclass("noh log element").addclass(a);this.add(c)};noh.log.little=function(){return new noh.log.Little};noh.log.slittle=function(a){var b=noh.log.little();a=noh.sleepy(b,a);a.log_=a.log;a.log=function(a,b){this.log_(a,b);this.wake()};return a};noh.log.IConsole=function(){};noh.log.IConsole.prototype.log=function(a){};noh.log.IConsole.prototype.info=function(a){};
noh.log.IConsole.prototype.warn=function(a){};noh.log.IConsole.prototype.error=function(a){};noh.log.L2C=function(a){this.logger=a};noh.log.L2C.prototype.log=function(a){this.logger.log("info",arguments)};noh.log.L2C.prototype.info=function(a){this.logger.log("info",arguments)};noh.log.L2C.prototype.warn=function(a){this.logger.log("warning",arguments)};noh.log.L2C.prototype.error=function(a){this.logger.log("error",arguments)};noh.log.L2C.prototype.debug=function(a){this.logger.log("debug",arguments)};
noh.log.L2C.prototype.install=function(){window.console=this};noh.log.l2c=function(a){return new noh.log.L2C(a)};noh.log.C2L=function(a){this.console=a};noh.log.C2L.prototype.log=function(a,b){/error/.test(a)?this.console.error.apply(this.console,b):/warning/.test(a)?this.console.warn.apply(this.console,b):/debug/.test(a)&&this.console.debug instanceof Function?this.console.debug.apply(this.console,b):this.console.info.apply(this.console,b)};noh.log.c2l=function(a){return new noh.log.C2L(a)};
noh.log.Multi=function(a){this.loggers=a};noh.log.Multi.prototype.log=function(a,b){for(var c=0;c<this.loggers.length;++c)this.loggers[c].log(a,b)};noh.log.multi=function(a){return new noh.log.Multi(a)};noh.log.Filter=function(a,b){this.logger=a;this.filter=b};noh.log.Filter.prototype.log=function(a,b){this.logger.log(a,this.filter(b))};noh.log.filter=function(a,b){return new noh.log.Filter(a,b)};
noh.log.addtime=function(a){return noh.log.filter(a,function(a){var c=new Date;return["["+noh.str.prefix(""+c.getHours(),"0",2)+":"+noh.str.prefix(""+c.getMinutes(),"0",2)+":"+noh.str.prefix(""+c.getSeconds(),"0",2)+"]"].concat(Array.prototype.slice.call(a,0))})};noh.log.limitlen=function(a,b){return noh.log.filter(a,function(a){a=noh.log.data2str(a);return[noh.str.limitlen(a,b)]})};
noh.log.reel=function(a,b){for(var c=2*a+1,d=void 0===b?1E4:b,e=[],f=0;f<c;++f)e.push(noh.log.slittle(d));c=noh.reel(a,"automatic","automatic",e);c.select(a-1);d=noh.div(c).addclass("noh log reel");d.reel=c;d.log=function(a,b){this.reel.getelem(this.reel.lines)[0].log(a,b);this.reel.rotate(-1)};d.setlines=function(a){var b=a-this.reel.lines;this.reel.lines=a;this.reel.rotate(b)};return d};
noh.cmdline=function(a,b){var c=b||'alert("hello world")',d=noh.input().attr("type","text").attr("size",a).attr("placeholder",c).addclass("noh cmdline"),c=noh.button(String.fromCharCode(8629)).attr("title","Press enter to run the command.").addclass("noh cmdline"),e=noh.div(d,c).css("display","inline-block").addclass("noh cmdline");e.run=function(){var a=d.$.val();console.log(a);try{var b=eval(a);void 0!==b&&console.log(b)}catch(c){console.error(c)}d.$.val("")};e.type=function(a){d.$.val(a)};e.focus=
function(){d.$.focus()};d.on("keypress",function(a){13==a.which&&e.run()});c.on("click",function(){e.run()});return e};
noh.objtest=function(a,b){for(var c=noh.table1r({style:"border: 6px ridge green"},noh.td(a)),d=[],e=0;e<b.length;++e){var f=noh.button(b[e]).addclass("noh button").attr("title",'Prepare the "'+b[e]+'" command to run.');f.on("click",function(){window.obj=a;g.type(this.textContent);g.focus()});d.push(f);d.push(noh.br())}var g=noh.cmdline(60,"obj.some_method()");return noh.div(noh.p(c),noh.p(g),noh.p(d))};noh.ISelectable=function(){};noh.ISelectable.prototype.selected=function(){};
noh.ISelectable.prototype.toggle=function(){};noh.MenuItem=function(a){noh.Element.call(this,"div",{"class":"noh menu item"},a);this.on("click",function(){this.noh.toggle();return!1})};noh.MenuItem.prototype=new noh.Element("div");noh.MenuItem.prototype.toggle=function(){this.toggleclass("selected")};noh.MenuItem.prototype.selected=function(){return this.hasclass("selected")};noh.menuitem=function(a){return new noh.MenuItem(a)};
noh.bigmenuitem=function(a,b){var c=noh.oneof(b),d=noh.div(noh.div(a),noh.div(c));a.toggle_orig_=a.toggle;a.toggle=function(){d.toggle()};d.toggle=function(){a.toggle_orig_();c.select(this.selected()?0:-1)};d.selected=function(){return a.selected()};return d};
noh.Menu=function(a){var b=noh.organize(arguments);noh.Element.call(this,"div",b.attrs,b.nodes);this.items_=b.nodes;for(b=0;b<this.items_.length;++b){var c=this.items[b];c.selected()&&c.toggle();c.menu_=this;c.menuIdx_=b;c.toggle_orig_=c.toggle;c.toggle=function(){this.menu_.select(this.selected()?-1:this.menuIdx_)}}this.selected_=-1};noh.Menu.prototype=new noh.Element("div");noh.Menu.prototype.selected=function(){return this.selected_};
noh.Menu.prototype.select=function(a){-1!=this.selected_&&this.items_[this.selected_].toggle_orig_();this.selected_=a;-1!=a&&this.items_[a].toggle_orig_()};noh.menu=function(a){return new noh.Menu(arguments)};noh.submenu=function(a,b){var c=noh.bigmenuitem(a,b);c.menu=b;return c};function noh_insects_init(){var a=$("#noh_insects");0!=a.length&&noh_insects().attachToDOM(a[0])}$(document).ready(noh_insects_init);function tdiv(a){return noh.div({"class":"noh stest"},arguments)}function runstest(a){a=a();return tdiv(a)}function runstests(a){var b=[],c;for(c in a)b.push(noh.dt(noh.fancy(noh.h3({id:"stest_"+c},"stest: ",c))).css("padding","20px"),noh.dd(runstest(a[c])));return noh.dl(b)}
function stests_toc(a){var b={"class":"noh link",style:"padding: 5px"},c=[],d;for(d in a)a=noh.a(b,d),a.scroll_target="#stest_"+d,a.on("click",function(){$(this.noh.scroll_target)[0].noh.scroll()}),c.push(noh.li(a));return noh.ul(c)}function noh_insects(){return noh.div(noh.fancy(noh.h1("NOH Insects")),noh.p("Please check the ",noh.a({href:"noh_doc.html"},"documentation")," first."),noh.fancy(noh.h3("TOC")),stests_toc(tests),runstests(tests))}
var tests={simple:function(){return noh.ex.simple()},goofy:function(){return noh.ex.goofy()},silly:function(){return noh.ex.silly()},whitey:function(){return noh.ex.whitey()},shiny:function(){return noh.ex.shiny()},shiny:function(){return noh.ex.shiny()},idiots:function(){return noh.ex.idiots()},colors:function(){return noh.div(noh.sdiv(noh.ex.color("red")),noh.sdiv(noh.ex.color("green")),noh.sdiv(noh.ex.color("blue")))},rainbows:function(){return noh.div(noh.sdiv(noh.ex.rainbow(5)),noh.sdiv(noh.ex.rainbow(10)),
noh.sdiv(noh.ex.rainbow(15)))},sleepy:function(){var a=noh.sleepy(noh.ex.simple(),2E3);return noh.objtest(a,["obj.wake()","obj.sleep()",'obj.parent.addclass("smooth")','obj.parent.remclass("smooth")'])},overlay_logger_cmd:function(){var a=noh.log.reel(15).addclass("pretty");install_logger(a);var b=noh.cmdline(40).addclass("pretty"),a=noh.overlay(a,b);a.addclass("bottom");a.css("right","10px");b=noh.objtest(a,'obj.show();obj.hide();obj.show(1);obj.hide(1);obj.parent.addclass("smooth");obj.parent.remclass("smooth");obj.remclass("top").addclass("bottom");obj.remclass("bottom").addclass("top");obj.css("right", "30px");obj.css("right", "230px")'.split(";"));
a.parent.addclass("smooth");return b}};function install_logger(a){noh.log.l2c(noh.log.multi([noh.log.c2l(window.console),noh.log.limitlen(noh.log.addtime(a),40)])).install()};
