function c(a){return new e("div",arguments)}function g(a){return new e("p",arguments)}function h(a){return new e("a",arguments)}function k(a){return new e("strong",arguments)}function l(a){return new e("dl",arguments)}function m(a){return new e("dt",arguments)}function n(a){return new e("dd",arguments)}function p(a){return new e("h1",arguments)}function q(a){return new e("h4",arguments)}function r(a){return new e("b",arguments)}function s(a){return new e("pre",arguments)}
function t(a,b,d){b=void 0===b?0:b;d=d?d:{d:{},c:[]};if(a instanceof u)d.c.push(a);else if("string"===typeof a)d.c.push(new v(a));else if(w(a))for(;b<a.length;++b)t(a[b],0,d);else if(a instanceof Object)$.extend(d.d,a);else if(void 0!==a&&null!==a)throw new TypeError("Unknown argument type: "+typeof a+" value: "+String(a));return d}function x(a){for(var b=["h1","h2","h3","h4"],d=0;d<b.length;++d)if(a==b[d])return d;return-1}
function w(a){if(void 0==a||null==a)return!1;if(a instanceof jQuery||jQuery.isArray(a))return!0;var b=a.length;if("number"!==typeof b)return!1;if(0==b)return!0;if(0>b)return!1;var d=Object.prototype.hasOwnProperty;return d.call(a,0)&&d.call(a,b-1)?!0:!1}function u(){this.length=0;this.b=this.a=this.parent=null}u.prototype.add=function(a){this.a.appendChild(a.a);a.parent=this;Array.prototype.push.call(this,a);return this};
function v(a){this.text=a;u.call(this);this.a=document.createTextNode(a);this.a.e=this;this.b=$(this.a)}v.prototype=new u;function e(a,b){this.tag=a;u.call(this);this.a=document.createElement(a);this.a.e=this;this.b=$(this.a);var d=t(arguments,1),f;for(f in d.d)this.attr(f,d.d[f]);for(f=0;f<d.c.length;++f)this.add(d.c[f])}e.prototype=new u;e.prototype.attr=function(a,b){this.b.attr(a,b);return this};e.prototype.on=function(a,b){this.b.on(a,b);return this};
function y(a,b){$("html,body").animate({scrollTop:a},b?b:1E3)}e.prototype.scroll=function(a){y(this.b.offset().top,a);return this};function z(a,b){return s({"class":"brush: "+a+"; toolbar: false"},b)}new e("div");new e("div");new e("div");function A(){var a=p("NOH");a.b.addClass("fancy");if(-1!=x(a.tag))a.on("click",function(){this.e.scroll()});else if("a"==a.tag){var b=a.b.attr("href");if(b&&0<b.length&&"#"==b[0])a.on("click",function(){y($($(this).attr("href")).offset().top)})}return a}
(function(){e.call(this,"div");this.b.addClass("noh log little")}).prototype=new e("div");new e("div");new e("div");$(document).ready(function(){var a=$("#noh_doc");if(0!=a.length){var b=c({style:"margin:10px"},A(),q("(No HTML library)"),g("The ",k("NOH")," library allows to create the HTML documents dynamicly in pure JavaScript ","(with almost no HTML code at all). "),g("The basic idea is that for every HTML tag, we have special JavaScript function, that generates appropriate DOM element."),g(q("Example:"),l(m("Instead of HTML code like this:"),n(z("html",'<div id="someid">\n    <h2>EXAMPLE</h2>\n    <p>\n        <h4>Some header</h4>\n        Some content\n    </p>\n    <p>\n        <h4>Other header</h4>\n        Other content\n    </p>\n</div>\n')),
m("We write JS code like this:"),n(z("js",'noh.div({id:"someid"},\n    noh.h2("EXAMPLE"),\n    noh.p(noh.h4("Some header"),"Some content"),\n    noh.p(noh.h4("Other header"),"Other content")\n)\n')))),g("We have a function for every HTML element like: ",z("js","noh.table, noh.tr, noh.td, noh.div, noh.span etc..; "),"but also we have functions that constructs many specialized and more complex Nodes that have some dynamic behaviour ","implemented like: ",z("js","noh.menu, noh.oneof, noh.details, noh.syntaxhl, noh.srccode, noh.llogger, noh.plogger")),
g("TODO: more introduction - how it replaces templates (there are other libraries, but...), that many times it's better to generate content from js because html is verbose (long download) etc.."),g("TODO: more examples - with not standard tags, but still simple; with attributes and styles; different ways to insert attributes and nodes - a few examples giving the same result"),g("TODO: about initialization; about options; about pollute:true and why we should avoid it in bigger projects;"),g("TODO: example that adds some dynamic behavoiur, and serves as a kind of template"),
g("TODO: About compiled versions of pages - min1, min2, min3"),g("The NOH library requires a jQuery library. (tested on: jquery-1.10.2.js)"),g("Please check the ",h({href:"noh_tests.html"},r("noh_tests.html"))," file! It demonstrates all available elements in action."),g("Additional API documentation generated with ",h({href:"http://usejsdoc.org/"},"jsdoc3")," will be available here: ",h({href:"apidoc/index.html"},"NOH API documentation")));a[0].appendChild(b.a);window.SyntaxHighlighter&&window.SyntaxHighlighter.all()}});
