noh={Q:function(a){a&&(this.message=a)}};noh.Q.prototype=Error("Not implemented");noh.ba=function(a){a&&(this.message=a)};noh.ba.prototype=new noh.Q("Operation not supported");noh.Aa="html head body script meta title link div p span a img br hr em i strong table tr th td thead tbody tfoot colgroup col ul ol li dl dt dd h1 h2 h3 h4 h5 h6 form fieldset input textarea label select option b pre code button kbd".split(" ");noh.body=function(a){return new noh.a("body",arguments)};
noh.link=function(a){return new noh.a("link",arguments)};noh.d=function(a){return new noh.a("div",arguments)};noh.Y=function(a){return new noh.a("p",arguments)};noh.span=function(a){return new noh.a("span",arguments)};noh.ca=function(a){return new noh.a("a",arguments)};noh.Xa=function(a){return new noh.a("img",arguments)};noh.Fa=function(a){return new noh.a("br",arguments)};noh.Ua=function(a){return new noh.a("hr",arguments)};noh.Oa=function(a){return new noh.a("em",arguments)};
noh.Va=function(a){return new noh.a("i",arguments)};noh.lb=function(a){return new noh.a("strong",arguments)};noh.table=function(a){return new noh.a("table",arguments)};noh.J=function(a){return new noh.a("tr",arguments)};noh.qb=function(a){return new noh.a("th",arguments)};noh.o=function(a){return new noh.a("td",arguments)};noh.rb=function(a){return new noh.a("thead",arguments)};noh.tbody=function(a){return new noh.a("tbody",arguments)};noh.pb=function(a){return new noh.a("tfoot",arguments)};
noh.Ja=function(a){return new noh.a("colgroup",arguments)};noh.Ia=function(a){return new noh.a("col",arguments)};noh.sb=function(a){return new noh.a("ul",arguments)};noh.cb=function(a){return new noh.a("ol",arguments)};noh.Za=function(a){return new noh.a("li",arguments)};noh.Ma=function(a){return new noh.a("dl",arguments)};noh.Na=function(a){return new noh.a("dt",arguments)};noh.Ka=function(a){return new noh.a("dd",arguments)};noh.ga=function(a){return new noh.a("h1",arguments)};
noh.Ra=function(a){return new noh.a("h2",arguments)};noh.V=function(a){return new noh.a("h3",arguments)};noh.ha=function(a){return new noh.a("h4",arguments)};noh.Sa=function(a){return new noh.a("h5",arguments)};noh.Ta=function(a){return new noh.a("h6",arguments)};noh.form=function(a){return new noh.a("form",arguments)};noh.Qa=function(a){return new noh.a("fieldset",arguments)};noh.input=function(a){return new noh.a("input",arguments)};noh.ob=function(a){return new noh.a("textarea",arguments)};
noh.label=function(a){return new noh.a("label",arguments)};noh.select=function(a){return new noh.a("select",arguments)};noh.eb=function(a){return new noh.a("option",arguments)};noh.Da=function(a){return new noh.a("b",arguments)};noh.ra=function(a){return new noh.a("pre",arguments)};noh.code=function(a){return new noh.a("code",arguments)};noh.button=function(a){return new noh.a("button",arguments)};noh.ja=function(a){return new noh.a("kbd",arguments)};noh.text=function(a){return new noh.R(a)};
noh.j=function(a,b,c){c=c?c:{i:{},c:[]};if(a instanceof noh.l)c.c.push(a);else if("string"===typeof a)c.c.push(noh.text(a));else if(noh.m.ia(a))for(b=void 0===b?0:b;b<a.length;++b)noh.j(a[b],0,c);else if(a instanceof Object)$.extend(c.i,a);else if(void 0!==a&&null!==a)throw new TypeError("Unknown argument type: "+typeof a+" value: "+String(a));return c};noh.m={};noh.m.push=function(a,b){return b.push.apply(b,a)};noh.m.indexOf=function(a,b){for(var c=0;c<b.length;++c)if(a==b[c])return c;return-1};
noh.m.Ca=function(a,b){if(null===b)return null;for(var c={},d=0;d<a.length;++d)c[a[d]]=b[d];return c};noh.m.bb=function(a,b){if(null===b)return null;for(var c=[],d=0;d<a.length;++d)c.push(b[a[d]]);return c};noh.m.ia=function(a){var b=Object.prototype.hasOwnProperty,c;return null!=a&&(a instanceof jQuery||"number"===typeof(c=a.length)&&(0<=c&&b.call(a,0)&&b.call(a,c-1)||jQuery.isArray(a)))};noh.s={};noh.s.W=function(a,b){a.length>b&&(a=a.substr(0,b-3)+"...");return a};
noh.s.prefix=function(a,b,c){for(;a.length<c;)a=b+a;return a};noh.l=function(){this.length=0;this.b=this.g=this.parent=null};noh.l.prototype.add=function(a){this.g.appendChild(a.g);a.parent=this;Array.prototype.push.call(this,a);return this};noh.R=function(a){this.text=a;noh.l.call(this);this.g=document.createTextNode(a);this.g.H=this;this.b=$(this.g)};noh.R.prototype=new noh.l;
noh.a=function(a,b){this.tag=a;noh.l.call(this);this.g=document.createElement(a);this.g.H=this;this.b=$(this.g);var c=noh.j(arguments,1),d;for(d in c.i)this.attr(d,c.i[d]);for(d=0;d<c.c.length;++d)this.add(c.c[d])};noh.a.prototype=new noh.l;noh.a.prototype.attr=function(a,b){this.b.attr(a,b);return this};noh.a.prototype.css=function(a,b){this.b.css(a,b);return this};noh.a.prototype.on=function(a,b){this.b.on(a,b);return this};function e(a,b){a.b.addClass(b);return a}
function h(a,b){a.b.removeClass(b);return a}noh.scroll=function(a,b){$("html,body").animate({scrollTop:a},b?b:1E3)};noh.a.prototype.scroll=function(a){noh.scroll(this.b.offset().top,a);return this};noh.xa=function(a){var b=noh.j(arguments);return noh.table(b.i,noh.tbody(noh.J(b.c)))};noh.nb=function(a){for(var b=noh.j(arguments),c=[],d=0;d<b.children.length;++d)c.push(j.o(b.c[d]));return noh.xa({"class":"noh bar"},b.i,c)};
noh.hb=function(a){return noh.d({style:"margin:10px; padding:10px; border:solid 2px"},arguments)};noh.f={};noh.f.ta=function(){return noh.span("Simpleeeee! kind of man!").css("padding",10).css("background-color","lightgray").css("border","solid 2px")};noh.f.fa=function(){return noh.span("Daaaaa..").css("padding",20).css("background-color","gray").css("border","solid 4px")};
noh.f.sa=function(){return noh.span({style:"padding: 25px; font-size:xx-large; color:red; background-color:yellow; border:solid 1px red; border-radius:40px"},":-)")};noh.f.tb=function(){return noh.span({style:"padding:15px; color:white; background-color:white; border:solid 2px white"},"White on white")};noh.f.jb=function(){return noh.span({style:"padding:10px; color:red; background-color:pink; border:solid 2px red"},":*")};noh.f.Wa=function(){return noh.d(noh.f.ta(),noh.f.fa(),noh.f.sa())};
noh.f.color=function(a){return noh.span({style:"padding:8px"},"C").css("color",a).css("background-color",a)};noh.f.gb=function(a){for(var b=[],c=0;c<a;++c)b.push(noh.f.color("hsl("+360*c/a+",100%,50%)"));return noh.span(b)};noh.wa=function(a){return noh.ra({"class":"brush: js; toolbar: false"},a)};noh.kb=function(a){return noh.wa(a.toString())};
noh.fb=function(a){var b=e(noh.d(arguments),"noh overlay");b.show=function(a){a=void 0===a?this:this[a];if(!a.b.hasClass("hidden"))return b;(this.b.hasClass("left")||this.b.hasClass("right"))&&a.css("left","").css("right","");(this.b.hasClass("top")||this.b.hasClass("bottom"))&&a.css("top","").css("bottom","");e(h(a,"hidden"),"visible");return this};b.hide=function(a){a=void 0===a?this:this[a];if(a.b.hasClass("hidden"))return b;var d=$(window).width(),f=$(window).height(),g=a.b.outerWidth(!0),m=a.b.outerHeight(!0),
k=a.b.offset(),n=k.left,k=k.top-$(document).scrollTop(),d=d-n-g,f=f-k-m;this.b.hasClass("left")?a.css("left",""+(-n-g-5)+"px"):this.b.hasClass("right")?a===this?a.css("right",""+(-d-g-5)+"px"):a.css("left",""+(g+d+5)+"px"):this.b.hasClass("top")?a.css("top",""+(-k-m-5)+"px"):this.b.hasClass("bottom")&&(a===this?a.css("bottom",""+(-f-m-5)+"px"):a.css("top",""+(m+f+5)+"px"));e(h(a,"visible"),"hidden");return this};return b};
noh.ua=function(a,b){e(e(a,"noh"),"sleepy");a.da=void 0===b?1E3:b;a.za=function(){e(h(this,"asleep"),"awake");window.clearTimeout(this.I);this.I=window.setTimeout(function(){a.$()},a.da)};a.$=function(){window.clearTimeout(this.I);this.I=void 0;e(h(this,"awake"),"asleep")};a.$();return a};noh.M=function(){};noh.M.prototype.F=function(){};noh.M.prototype.r=function(){};
noh.u=function(a){var b=e(noh.d(arguments),"noh blind content");noh.a.call(this,"div",b);e(this,"noh blind");this.t=b;this.r(!1);var c=this;this.b.show(function(){c.r(c.F())})};noh.u.prototype=new noh.a("div");noh.u.prototype.F=function(){return this.ea};
noh.u.prototype.r=function(a){var b=this.b,c=this.t.b,d=c.width(),f=c.height();c.css("clip","rect(0px "+d+"px "+(a?f:0)+"px 0px");a?(h(this.t,"hidden"),e(this.t,"visible")):(h(this.t,"visible"),e(this.t,"hidden"));b.width(d);b.height(a?f:0);this.ea=a;return this};noh.S=function(a){return new noh.u(arguments)};noh.N=function(){};noh.N.prototype.selected=function(){};noh.N.prototype.select=function(){};
noh.B=function(a){for(var b=noh.j(arguments),c=0;c<b.c.length;++c){var d=noh.S(b.c[c]);b.c[c]=d;d.pa=c}noh.a.call(this,"div",b.i,b.c);e(this,"noh oneof");this.e=-1};noh.B.prototype=new noh.a("div");noh.B.prototype.selected=function(){return this.e};noh.B.prototype.select=function(a){a instanceof noh.l?a=a.pa:null===a&&(a=-1);var b=this.length;if(-1>a||a>=b)a=-1;-1!=this.e&&this[this.e].r(!1);-1!=a&&this[a].r(!0);this.e=a;return this};noh.qa=function(a){return new noh.B(arguments)};
noh.La=function(a){var b=e(noh.d(arguments),"noh details content"),c=noh.S(b),b=e(noh.button("details..."),"noh details button").attr("title","show/hide details");b.on("click",function(){c.r(!c.F())});return e(noh.d(noh.d(b),noh.d(c)),"noh details")};
noh.q=function(a,b,c,d){for(var f=noh.j(arguments,3),g=0;g<f.c.length;++g){var m=e(noh.d(f.c[g]),"noh reel element");f.c[g]=m}noh.a.call(this,"div",f.i,f.c);e(this,"noh reel");this.h=a;this.rotation=0;this.width=b;this.height=c;l(this);var k=this;this.b.show(function(){k.update()});this.e=-1};noh.q.prototype=new noh.a("div");noh.q.prototype.selected=function(){return this.e};
noh.q.prototype.select=function(a){if(-1>a||a>=this.length)a=-1;if(this.e==a)return this;-1!=this.e&&h(p(this,this.e),"selected");-1!=a&&e(p(this,a),"selected");this.e=a;return this};
function l(a){var b=0;if("automatic"==a.width)for(var c=0;c<a.length;++c)esize=a[c].b.width(),esize>b&&(b=esize);else if("dynamic"==a.width)for(c=0;c<a.h;++c)esize=p(a,c).b.width(),esize>b&&(b=esize);else b=a.width;a.css("min-width",b).css("max-width",b).css("width",b);b=0;if("automatic"==a.height){for(c=0;c<a.length;++c)esize=a[c].b.height(),esize>b&&(b=esize);b*=a.h}else if("dynamic"==a.height){for(c=0;c<a.h;++c)esize=p(a,c).b.height(),esize>b&&(b=esize);b*=a.h}else b=a.height;a.css("min-height",
b).css("max-height",b).css("height",b);a.U=b}function q(a,b){for(;0>b;)b+=a.length;for(;b>=a.length;)b-=a.length;return b}function p(a,b){return a[q(a,b-a.rotation)]}
noh.q.prototype.update=function(a){void 0!==a&&(this.h=a);l(this);for(a=0;a<this.length;++a){var b=p(this,a);h(b,"selected");a<this.h?(e(h(b,"hidden"),"visible"),b.css("top",""+a*this.U/this.h+"px")):(e(h(b,"visible"),"hidden"),b.css("top",""+(this.length-a-1)*this.U/(this.length-this.h)+"px"))}-1!=this.e&&e(p(this,this.e),"selected");return this};noh.q.prototype.rotate=function(a){this.rotation=q(this,this.rotation+a);return this.update()};
noh.k=function(a,b,c,d){var f=noh.j(arguments,3);return new noh.q(a,b,c,f.i,f.c)};noh.Pa=function(a){e(a,"fancy");if(-1!=noh.m.indexOf(a.tag,["h1","h2","h3","h4"]))a.on("click",function(){this.H.scroll()});return a};noh.ya=function(a){var b=/(https?|ftp):\/\//;a=a.split(/\s+/).map(function(a){return b.test(a)?noh.ca({href:a,target:"_blank"},a):" "+a+" "});return noh.ja(a)};noh.log={};noh.log.T=function(a){var b="";0<a.length&&(b+=a[0]);for(var c=1;c<a.length;++c)b=b+" "+a[c].toString();return b};
noh.log.aa=function(){};noh.log.aa.prototype.log=function(){};noh.log.D=function(){noh.a.call(this,"div");e(this,"noh log little")};noh.log.D.prototype=new noh.a("div");noh.log.D.prototype.log=function(a,b){if(this.length){var c=Array.prototype.pop.call(this);c.parent=null;this.g.removeChild(c.g)}c=e(e(noh.ya(noh.log.T(b)),"noh log element"),a);this.add(c)};noh.log.ka=function(){return new noh.log.D};
noh.log.va=function(a){var b=noh.log.ka();a=noh.ua(b,a);a.la=a.log;a.log=function(a,b){this.la(a,b);this.za()};return a};noh.log.v=function(){};noh.log.v.prototype.log=function(){};noh.log.v.prototype.info=function(){};noh.log.v.prototype.warn=function(){};noh.log.v.prototype.error=function(){};noh.log.p=function(a){this.n=a};noh.log.p.prototype.log=function(a){this.n.log("info",arguments)};noh.log.p.prototype.info=function(a){this.n.log("info",arguments)};
noh.log.p.prototype.warn=function(a){this.n.log("warning",arguments)};noh.log.p.prototype.error=function(a){this.n.log("error",arguments)};noh.log.p.prototype.debug=function(a){this.n.log("debug",arguments)};noh.log.Ya=function(a){return new noh.log.p(a)};noh.log.K=function(a){this.console=a};
noh.log.K.prototype.log=function(a,b){/error/.test(a)?this.console.error.apply(this.console,b):/warning/.test(a)?this.console.warn.apply(this.console,b):/debug/.test(a)&&this.console.debug instanceof Function?this.console.debug.apply(this.console,b):this.console.info.apply(this.console,b)};noh.log.Ga=function(a){return new noh.log.K(a)};noh.log.P=function(a){this.X=a};noh.log.P.prototype.log=function(a,b){for(var c=0;c<this.X.length;++c)this.X[c].log(a,b)};noh.log.ab=function(a){return new noh.log.P(a)};
noh.log.L=function(a,b){this.n=a;this.filter=b};noh.log.L.prototype.log=function(a,b){this.n.log(a,this.filter(b))};noh.log.filter=function(a,b){return new noh.log.L(a,b)};noh.log.Ba=function(a){return noh.log.filter(a,function(a){var c=new Date;return["["+noh.s.prefix(""+c.getHours(),"0",2)+":"+noh.s.prefix(""+c.getMinutes(),"0",2)+":"+noh.s.prefix(""+c.getSeconds(),"0",2)+"]"].concat(Array.prototype.slice.call(a,0))})};
noh.log.W=function(a,b){return noh.log.filter(a,function(a){return[noh.s.W(noh.log.T(a),b)]})};noh.log.k=function(a,b){for(var c=2*a+1,d=void 0===b?1E4:b,f=[],g=0;g<c;++g)f.push(noh.log.va(d));c=noh.k(a,"automatic","automatic",f);c.select(a-1);logger=e(noh.d(c),"noh log reel");logger.k=c;logger.log=function(a,b){p(this.k,this.k.h)[0].log(a,b);this.k.rotate(-1)};logger.ib=function(a){var b=a-this.k.h;this.k.h=a;this.k.rotate(b)};return logger};
noh.Ha=function(a){var b=e(noh.input().attr("type","text").attr("size",a).attr("placeholder",'alert("hello world")'),"noh cmdline");a=e(noh.button(String.fromCharCode(8629)).attr("title","Press enter to run the command."),"noh cmdline");var c=e(noh.d(b,a).css("display","inline-block"),"noh cmdline");c.Z=function(){var a=b.b.val();console.log(a);try{var c=eval(a);void 0!==c&&console.log(c)}catch(g){console.error(g)}b.b.val("")};b.on("keypress",function(a){13==a.which&&c.Z()});a.on("click",function(){c.Z()});
return c};noh.O=function(){};noh.O.prototype.selected=function(){};noh.O.prototype.toggle=function(){};noh.A=function(a){noh.a.call(this,"div",{"class":"noh menu item"},a);this.on("click",function(){this.H.toggle();return!1})};noh.A.prototype=new noh.a("div");noh.A.prototype.toggle=function(){this.b.toggleClass("selected")};noh.A.prototype.selected=function(){return this.b.hasClass("selected")};noh.$a=function(a){return new noh.A(a)};
noh.Ea=function(a,b){var c=noh.qa(b),d=noh.d(noh.d(a),noh.d(c));a.C=a.toggle;a.toggle=function(){d.toggle()};d.toggle=function(){a.C();c.select(this.selected()?0:-1)};d.selected=function(){return a.selected()};return d};noh.w=function(a){var b=noh.j(arguments);noh.a.call(this,"div",b.i,b.c);this.G=b.c;for(b=0;b<this.G.length;++b){var c=this.items[b];c.selected()&&c.toggle();c.oa=this;c.na=b;c.C=c.toggle;c.toggle=function(){this.oa.select(this.selected()?-1:this.na)}}this.e=-1};noh.w.prototype=new noh.a("div");
noh.w.prototype.selected=function(){return this.e};noh.w.prototype.select=function(a){-1!=this.e&&this.G[selected_].C();this.e=a;-1!=a&&this.G[a].C()};noh.ma=function(a){return new noh.w(arguments)};noh.mb=function(a,b){var c=bigmenuitem(a,b);c.ma=b;return c};function r(a){var b=noh.j(arguments);return noh.d({style:"margin: 25px; padding:15px; border: double"},b.i,b.c)}
$(document).ready(function(){var a=document.getElementById("noh_example"),b=noh.d(noh.ga("Simple NOH example"),noh.ha("(check the noh_example.js file)"),noh.Y("TODO: add some styles, borders etc; add some function that acts as a kind of a template"),r(noh.V("Lets check out some table"),noh.table(noh.J(noh.o("first cell in first row"),noh.o("second cell in first row"),noh.o("third cell in first row")),noh.J(noh.o("first cell in second row"),noh.o("second cell in second row"),noh.o("third cell in second row")))),
r(noh.V("Now lets check out some inputs"),noh.input({type:"text"}),noh.input({type:"button"}),noh.input({type:"checkbox"}),noh.input({type:"color"}),noh.input({type:"date"}),noh.input({type:"file"}),noh.input({type:"radio"}),noh.input({type:"time"}),noh.input({type:"week"}),noh.Y("TODO: better inputs examples")));a.appendChild(b.g);$("td").css("border","solid")});
